import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 1.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/1.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'Saarländische Winterwurfmeisterschaften'),
        new Token(Type.COMPETITION_CITY, 'Saarbrücken'),
        new Token(Type.COMPETITION_VENUE, 'Leichtathletik-Halle'),
        new Token(Type.COMPETITION_START_DATE, '15.01.2017'),
        new Token(Type.DISCIPLINE_NAME, 'Hammerwurf'),
        new Token(Type.AGE_GROUP_NAME, 'Weibliche Jugend U18'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '3000g'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '15.01.2017'),
        new Token(Type.EVENT_TIME, '10:30'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '420'),
        new Token(Type.ATHLETE_FULL_NAME, 'Setter Hannah'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LV Merzig'),
        new Token(Type.PERFORMANCE, '51,20'),
        new Token(Type.ATTEMPT1, '44,85'),
        new Token(Type.ATTEMPT2, '49,93'),
        new Token(Type.ATTEMPT3, '51,20'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, '50,70'),
        new Token(Type.ATTEMPT6, '47,28'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '408'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hessling Lorena'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAC Saarlouis'),
        new Token(Type.PERFORMANCE, '43,26'),
        new Token(Type.ATTEMPT1, '40,96'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, '41,95'),
        new Token(Type.ATTEMPT4, '43,21'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, '43,26'),
        new Token(Type.DISCIPLINE_NAME, 'Hammerwurf'),
        new Token(Type.AGE_GROUP_NAME, 'Weibliche Jugend U20'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '4000g'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '15.01.2017'),
        new Token(Type.EVENT_TIME, '10:30'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '434'),
        new Token(Type.ATHLETE_FULL_NAME, 'Zott Katharina'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Limbach'),
        new Token(Type.PERFORMANCE, '51,52'),
        new Token(Type.ATTEMPT1, '51,52'),
        new Token(Type.ATTEMPT2, '50,70'),
        new Token(Type.ATTEMPT3, '51,44'),
        new Token(Type.ATTEMPT4, '50,00'),
        new Token(Type.ATTEMPT5, '50,71'),
        new Token(Type.ATTEMPT6, '50,88'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '432'),
        new Token(Type.ATHLETE_FULL_NAME, 'Zott Annalena'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Limbach'),
        new Token(Type.PERFORMANCE, '49,54'),
        new Token(Type.ATTEMPT1, '48,10'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, '44,80'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, '48,62'),
        new Token(Type.ATTEMPT6, '49,54'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '433'),
        new Token(Type.ATHLETE_FULL_NAME, 'Zott Franziska'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Limbach'),
        new Token(Type.PERFORMANCE, '48,54'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, '48,53'),
        new Token(Type.ATTEMPT3, 'x'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, '48,54'),
        new Token(Type.DISCIPLINE_NAME, 'Hammerwurf'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '5000g'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '15.01.2017'),
        new Token(Type.EVENT_TIME, '11:30'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '415'),
        new Token(Type.ATHLETE_FULL_NAME, 'Moll Konstantin'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LC Rehlingen'),
        new Token(Type.PERFORMANCE, '55,69'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, 'x'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, '55,69'),
        new Token(Type.ATTEMPT6, 'x'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '418'),
        new Token(Type.ATHLETE_FULL_NAME, 'Altpeter Lars'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LSG Sbr.-Sulzbachtal'),
        new Token(Type.PERFORMANCE, '46,40'),
        new Token(Type.ATTEMPT1, '43,75'),
        new Token(Type.ATTEMPT2, '45,17'),
        new Token(Type.ATTEMPT3, '46,40'),
        new Token(Type.ATTEMPT4, '44,28'),
        new Token(Type.ATTEMPT5, '44,06'),
        new Token(Type.ATTEMPT6, 'x'),
        new Token(Type.DISCIPLINE_NAME, 'Hammerwurf'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U20'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '6000g'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '15.01.2017'),
        new Token(Type.EVENT_TIME, '11:30'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '409'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hessling Fabio'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAC Saarlouis'),
        new Token(Type.PERFORMANCE, '62,79'),
        new Token(Type.ATTEMPT1, '62,79'),
        new Token(Type.ATTEMPT2, '62,35'),
        new Token(Type.ATTEMPT3, '60,61'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, 'x'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '419'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hoffmann Ken'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'LUX'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LV Merzig'),
        new Token(Type.PERFORMANCE, '52,94'),
        new Token(Type.ATTEMPT1, '51,76'),
        new Token(Type.ATTEMPT2, '52,40'),
        new Token(Type.ATTEMPT3, 'x'),
        new Token(Type.ATTEMPT4, '51,29'),
        new Token(Type.ATTEMPT5, '52,94'),
        new Token(Type.ATTEMPT6, '49,45'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '421'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kohlwey Nico'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LV Merzig'),
        new Token(Type.PERFORMANCE, '48,07'),
        new Token(Type.ATTEMPT1, '46,44'),
        new Token(Type.ATTEMPT2, '44,79'),
        new Token(Type.ATTEMPT3, '45,56'),
        new Token(Type.ATTEMPT4, '45,91'),
        new Token(Type.ATTEMPT5, '48,07'),
        new Token(Type.ATTEMPT6, '44,24'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '431'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hauck Tobias'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Homburg'),
        new Token(Type.PERFORMANCE, '47,61'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, '43,89'),
        new Token(Type.ATTEMPT3, '45,94'),
        new Token(Type.ATTEMPT4, '47,12'),
        new Token(Type.ATTEMPT5, '47,61'),
        new Token(Type.ATTEMPT6, '46,71'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
