import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 10.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/10.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'Rheinland-Pfalz Hallenmeisterschaften U20, U18'),
        new Token(Type.COMPETITION_CITY, 'Ludwigshafen'),
        new Token(Type.COMPETITION_VENUE, 'Leichtathletik Halle Ludwigshafen'),
        new Token(Type.COMPETITION_START_DATE, '22.01.2017'),
        new Token(Type.DISCIPLINE_NAME, '4x200m'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.EVENT_DATE, '22.01.2017'),
        new Token(Type.EVENT_TIME, '18:00'),
        new Token(Type.ROUND_NAME, 'Final'),
        new Token(Type.TEAM_POSITION, '1'),
        new Token(Type.TEAM_NAME, 'LG Rhein-Wied'),
        new Token(Type.TEAM_COUNTRY, 'GER'),
        new Token(Type.TEAM_CLUB_NAME, 'LG Rhein-Wied'),
        new Token(Type.PERFORMANCE, '1:37,87'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./II'),
        new Token(Type.ATHLETE_BIB, '577'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schröders Thorben'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_BIB, '570'),
        new Token(Type.ATHLETE_FULL_NAME, 'Dilla Julian'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_BIB, '573'),
        new Token(Type.ATHLETE_FULL_NAME, 'Jäger Lukas'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_BIB, '580'),
        new Token(Type.ATHLETE_FULL_NAME, 'Thomas Paul'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.TEAM_POSITION, '2'),
        new Token(Type.TEAM_NAME, 'TSV SCHOTT Mainz 1'),
        new Token(Type.TEAM_COUNTRY, 'GER'),
        new Token(Type.TEAM_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, '1:38,91'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./II'),
        new Token(Type.ATHLETE_BIB, '510'),
        new Token(Type.ATHLETE_FULL_NAME, 'Mombächer Laurent'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_BIB, '502'),
        new Token(Type.ATHLETE_FULL_NAME, 'Klecker Felix'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_BIB, '489'),
        new Token(Type.ATHLETE_FULL_NAME, 'Bogs Sven'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_BIB, '524'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wein Maurice'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.TEAM_POSITION, '3'),
        new Token(Type.TEAM_NAME, 'TV 1861 Bad Ems'),
        new Token(Type.TEAM_COUNTRY, 'GER'),
        new Token(Type.TEAM_CLUB_NAME, 'TV 1861 Bad Ems'),
        new Token(Type.PERFORMANCE, '1:46,56'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_BIB, '368'),
        new Token(Type.ATHLETE_FULL_NAME, 'Löffler Maximilian'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_BIB, '374'),
        new Token(Type.ATHLETE_FULL_NAME, 'Willrich Dominik'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_BIB, '370'),
        new Token(Type.ATHLETE_FULL_NAME, 'Poncelet Michael'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_BIB, '369'),
        new Token(Type.ATHLETE_FULL_NAME, 'Niebergall Erik'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.TEAM_NAME, 'LG Bernkastel/Wittlich'),
        new Token(Type.TEAM_COUNTRY, 'GER'),
        new Token(Type.TEAM_CLUB_NAME, 'LG Bernkastel/Wittlich'),
        new Token(Type.PERFORMANCE, 'disq.'),
        new Token(Type.ATHLETE_BIB, '380'),
        new Token(Type.ATHLETE_FULL_NAME, 'Ehlen Peter'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_BIB, '388'),
        new Token(Type.ATHLETE_FULL_NAME, 'Raadts Florian'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.COMMENT, 'IWR 170.7 1.Wechsel überlaufen'),
        new Token(Type.ATHLETE_BIB, '385'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hoinke Lukas'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_BIB, '386'),
        new Token(Type.ATHLETE_FULL_NAME, 'Moll Felix'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.TEAM_NAME, 'TSV SCHOTT Mainz 2'),
        new Token(Type.TEAM_COUNTRY, 'GER'),
        new Token(Type.TEAM_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, 'disq.'),
        new Token(Type.ATHLETE_BIB, '494'),
        new Token(Type.ATHLETE_FULL_NAME, 'Fastenrath Marc'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_BIB, '511'),
        new Token(Type.ATHLETE_FULL_NAME, 'Nelissen Luca'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.COMMENT, 'IWR 163.2 1.Wechsel'),
        new Token(Type.ATHLETE_BIB, '512'),
        new Token(Type.ATHLETE_FULL_NAME, 'Plantz Liam'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_BIB, '513'),
        new Token(Type.ATHLETE_FULL_NAME, 'Plicht Esra'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.DISCIPLINE_NAME, 'Hochsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '22.01.2017'),
        new Token(Type.EVENT_TIME, '10:00'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '439'),
        new Token(Type.ATHLETE_FULL_NAME, 'Unruh Jonas'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LC Hassloch'),
        new Token(Type.PERFORMANCE, '1,80'),
        new Token(Type.HEIGHT, '1,60'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,65'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,70'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,75'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,80'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,83'),
        new Token(Type.HEIGHT_RESULT, 'XX'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '632'),
        new Token(Type.ATHLETE_FULL_NAME, 'Keser Felix'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Westerwald'),
        new Token(Type.PERFORMANCE, '1,80'),
        new Token(Type.HEIGHT, '1,60'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,65'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,70'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,75'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,80'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,83'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '584'),
        new Token(Type.ATHLETE_FULL_NAME, 'Blessing Felix'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Rheinzabern'),
        new Token(Type.PERFORMANCE, '1,70'),
        new Token(Type.HEIGHT, '1,60'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,65'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,70'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,75'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '512'),
        new Token(Type.ATHLETE_FULL_NAME, 'Plantz Liam'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, '1,65'),
        new Token(Type.HEIGHT, '1,60'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,65'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,70'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '533'),
        new Token(Type.ATHLETE_FULL_NAME, 'Bruchhausen Marvin'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, '1,60'),
        new Token(Type.HEIGHT, '1,60'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '1,65'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.DISCIPLINE_NAME, 'Weitsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '22.01.2017'),
        new Token(Type.EVENT_TIME, '11:50'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '429'),
        new Token(Type.ATHLETE_FULL_NAME, 'Bieler Jan'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Freinsheim'),
        new Token(Type.PERFORMANCE, '6,81'),
        new Token(Type.ATTEMPT1, '6,62'),
        new Token(Type.ATTEMPT2, '6,56'),
        new Token(Type.ATTEMPT3, 'x'),
        new Token(Type.ATTEMPT4, '-'),
        new Token(Type.ATTEMPT5, '6,51'),
        new Token(Type.ATTEMPT6, '6,81'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '572'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hoffmann Luca'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Rhein-Wied'),
        new Token(Type.PERFORMANCE, '6,26'),
        new Token(Type.ATTEMPT1, '5,92'),
        new Token(Type.ATTEMPT2, '6,07'),
        new Token(Type.ATTEMPT3, '6,17'),
        new Token(Type.ATTEMPT4, '6,26'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, '6,17'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '580'),
        new Token(Type.ATHLETE_FULL_NAME, 'Thomas Paul'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Rhein-Wied'),
        new Token(Type.PERFORMANCE, '5,93'),
        new Token(Type.ATTEMPT1, '5,74'),
        new Token(Type.ATTEMPT2, '5,84'),
        new Token(Type.ATTEMPT3, '5,50'),
        new Token(Type.ATTEMPT4, '5,79'),
        new Token(Type.ATTEMPT5, '5,81'),
        new Token(Type.ATTEMPT6, '5,93'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '535'),
        new Token(Type.ATHLETE_FULL_NAME, 'Graffe Steffen'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, '5,77'),
        new Token(Type.ATTEMPT1, '5,77'),
        new Token(Type.ATTEMPT2, '5,47'),
        new Token(Type.ATTEMPT3, '5,18'),
        new Token(Type.ATTEMPT4, '-'),
        new Token(Type.ATTEMPT5, '-'),
        new Token(Type.ATTEMPT6, '-'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '643'),
        new Token(Type.ATHLETE_FULL_NAME, 'Lindinger Dominic'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TG Worms'),
        new Token(Type.PERFORMANCE, '5,64'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, '5,64'),
        new Token(Type.ATTEMPT3, 'x'),
        new Token(Type.ATTEMPT4, '5,46'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, '5,43'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '370'),
        new Token(Type.ATHLETE_FULL_NAME, 'Poncelet Michael'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV 1861 Bad Ems'),
        new Token(Type.PERFORMANCE, '5,62'),
        new Token(Type.ATTEMPT1, '5,60'),
        new Token(Type.ATTEMPT2, '5,47'),
        new Token(Type.ATTEMPT3, '5,41'),
        new Token(Type.ATTEMPT4, '5,22'),
        new Token(Type.ATTEMPT5, '5,62'),
        new Token(Type.ATTEMPT6, '5,61'),
        new Token(Type.ATHLETE_POSITION, '7'),
        new Token(Type.ATHLETE_BIB, '482'),
        new Token(Type.ATHLETE_FULL_NAME, 'Weber Johannes'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'ABC Ludwigshafen'),
        new Token(Type.PERFORMANCE, '5,60'),
        new Token(Type.ATTEMPT1, '5,54'),
        new Token(Type.ATTEMPT2, '5,41'),
        new Token(Type.ATTEMPT3, '5,57'),
        new Token(Type.ATTEMPT4, '5,60'),
        new Token(Type.ATTEMPT5, '-'),
        new Token(Type.ATTEMPT6, '5,48'),
        new Token(Type.END, undefined),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
