import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 11.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/11.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'Saarländische Hallenmeisterschaften'),
        new Token(Type.COMPETITION_CITY, 'Saarbrücken'),
        new Token(Type.COMPETITION_VENUE, 'Leichtathletik-Halle'),
        new Token(Type.COMPETITION_START_DATE, '15.01.2017'),
        new Token(Type.DISCIPLINE_NAME, '4x200m'),
        new Token(Type.AGE_GROUP_NAME, 'Männer'),
        new Token(Type.EVENT_DATE, '15.01.2017'),
        new Token(Type.EVENT_TIME, '16:45'),
        new Token(Type.ROUND_NAME, 'Zeitläufe'),
        new Token(Type.TEAM_POSITION, '1 (1)'),
        new Token(Type.TEAM_NAME, 'LAZ SAAR 05 Saarbrücken'),
        new Token(Type.TEAM_COUNTRY, 'GER'),
        new Token(Type.TEAM_CLUB_NAME, 'LAZ SAAR 05 Saarbrücken'),
        new Token(Type.PERFORMANCE, '1:27,02'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_BIB, '480'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hind Robert'),
        new Token(Type.ATHLETE_YOB, '1992'),
        new Token(Type.ATHLETE_BIB, '458'),
        new Token(Type.ATHLETE_FULL_NAME, 'Condé Ismail-Jean'),
        new Token(Type.ATHLETE_YOB, '1992'),
        new Token(Type.ATHLETE_BIB, '465'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kirstges Marcel'),
        new Token(Type.ATHLETE_YOB, '1991'),
        new Token(Type.ATHLETE_BIB, '456'),
        new Token(Type.ATHLETE_FULL_NAME, 'Balasubramaniam Thanusanth'),
        new Token(Type.ATHLETE_YOB, '1995'),
        new Token(Type.TEAM_POSITION, ' ()'),
        new Token(Type.TEAM_NAME, 'LC Rehlingen'),
        new Token(Type.TEAM_COUNTRY, 'GER'),
        new Token(Type.TEAM_CLUB_NAME, 'LC Rehlingen'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.ATHLETE_BIB, '996'),
        new Token(Type.ATHLETE_FULL_NAME, 'Feld Fabian'),
        new Token(Type.ATHLETE_YOB, '1994'),
        new Token(Type.ATHLETE_BIB, '990'),
        new Token(Type.ATHLETE_FULL_NAME, 'Lotz Jonas'),
        new Token(Type.ATHLETE_YOB, '1993'),
        new Token(Type.ATHLETE_BIB, '492'),
        new Token(Type.ATHLETE_FULL_NAME, 'Becker Christian'),
        new Token(Type.ATHLETE_YOB, '1995'),
        new Token(Type.ATHLETE_BIB, '991'),
        new Token(Type.ATHLETE_FULL_NAME, 'Seewald Kai'),
        new Token(Type.ATHLETE_YOB, '1995'),
        new Token(Type.DISCIPLINE_NAME, 'Hochsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Männer'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '15.01.2017'),
        new Token(Type.EVENT_TIME, '13:00'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '462'),
        new Token(Type.ATHLETE_FULL_NAME, 'Liefgen Sven'),
        new Token(Type.ATHLETE_YOB, '1995'),
        new Token(Type.ATHLETE_COUNTRY, 'LUX'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ SAAR 05 Saarbrücken'),
        new Token(Type.PERFORMANCE, '1,99'),
        new Token(Type.HEIGHT, '1,60'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,65'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,70'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,75'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,78'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,81'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,84'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,87'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,90'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,93'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,96'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,99'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,02'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '466'),
        new Token(Type.ATHLETE_FULL_NAME, 'Gaspar Charel'),
        new Token(Type.ATHLETE_YOB, '1991'),
        new Token(Type.ATHLETE_COUNTRY, 'LUX'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ SAAR 05 Saarbrücken'),
        new Token(Type.PERFORMANCE, '1,96'),
        new Token(Type.HEIGHT, '1,60'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,65'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,70'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,75'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,78'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,81'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,84'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,87'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,90'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,93'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,96'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '1,99'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,02'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.DISCIPLINE_NAME, 'Stabhochsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Männer'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '15.01.2017'),
        new Token(Type.EVENT_TIME, '12:30'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '1437'),
        new Token(Type.ATHLETE_FULL_NAME, 'Koehl Pascal'),
        new Token(Type.ATHLETE_YOB, '1991'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LA Team Saar'),
        new Token(Type.PERFORMANCE, '5,41'),
        new Token(Type.HEIGHT, '3,60'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '3,80'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,00'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,20'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,30'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,40'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,50'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,60'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,70'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,80'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,90'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '5,00'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '5,10'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '5,20'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '5,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '5,41'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '464'),
        new Token(Type.ATHLETE_FULL_NAME, 'Bollinger Marvin'),
        new Token(Type.ATHLETE_YOB, '1996'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ SAAR 05 Saarbrücken'),
        new Token(Type.PERFORMANCE, '4,60'),
        new Token(Type.HEIGHT, '3,60'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '3,80'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,00'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,20'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,30'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,40'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,50'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,60'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '4,70'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,80'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, 'aW'),
        new Token(Type.ATHLETE_BIB, '1408'),
        new Token(Type.ATHLETE_FULL_NAME, 'Lüsse Johannes'),
        new Token(Type.ATHLETE_YOB, '1985'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, '4,20'),
        new Token(Type.HEIGHT, '3,60'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '3,80'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,00'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '4,20'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '4,30'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.DISCIPLINE_NAME, 'Weitsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Männer'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '15.01.2017'),
        new Token(Type.EVENT_TIME, '14:15'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '465'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kirstges Marcel'),
        new Token(Type.ATHLETE_YOB, '1991'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ SAAR 05 Saarbrücken'),
        new Token(Type.PERFORMANCE, '7,59'),
        new Token(Type.ATTEMPT1, '7,59'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, 'x'),
        new Token(Type.ATTEMPT4, '7,54'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, '7,56'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '464'),
        new Token(Type.ATHLETE_FULL_NAME, 'Bollinger Marvin'),
        new Token(Type.ATHLETE_YOB, '1996'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ SAAR 05 Saarbrücken'),
        new Token(Type.PERFORMANCE, '7,02'),
        new Token(Type.ATTEMPT1, '6,97'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, '6,73'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, '7,02'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '1432'),
        new Token(Type.ATHLETE_FULL_NAME, 'Gillen Jonas'),
        new Token(Type.ATHLETE_YOB, '1990'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV St. Wendel'),
        new Token(Type.PERFORMANCE, '6,55'),
        new Token(Type.ATTEMPT1, '6,46'),
        new Token(Type.ATTEMPT2, '6,55'),
        new Token(Type.ATTEMPT3, '6,29'),
        new Token(Type.ATTEMPT4, '6,41'),
        new Token(Type.ATTEMPT5, '6,34'),
        new Token(Type.ATTEMPT6, '4,99'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '1373'),
        new Token(Type.ATHLETE_FULL_NAME, 'Tregellis Sidney-Spike'),
        new Token(Type.ATHLETE_YOB, '1994'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Bliestal'),
        new Token(Type.PERFORMANCE, '6,37'),
        new Token(Type.ATTEMPT1, '5,60'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, '6,37'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, '5,95'),
        new Token(Type.ATTEMPT6, '6,14'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '1391'),
        new Token(Type.ATHLETE_FULL_NAME, 'Müller Jannik'),
        new Token(Type.ATHLETE_YOB, '1997'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LSG Schmelz-Hüttersdorf'),
        new Token(Type.PERFORMANCE, '5,99'),
        new Token(Type.ATTEMPT1, '5,51'),
        new Token(Type.ATTEMPT2, '5,69'),
        new Token(Type.ATTEMPT3, 'x'),
        new Token(Type.ATTEMPT4, '5,91'),
        new Token(Type.ATTEMPT5, '5,71'),
        new Token(Type.ATTEMPT6, '5,99'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '1418'),
        new Token(Type.ATHLETE_FULL_NAME, 'Beiske Joshua'),
        new Token(Type.ATHLETE_YOB, '1989'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Dillingen'),
        new Token(Type.PERFORMANCE, '5,62'),
        new Token(Type.ATTEMPT1, '5,49'),
        new Token(Type.ATTEMPT2, '5,42'),
        new Token(Type.ATTEMPT3, '5,62'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, '5,49'),
        new Token(Type.ATHLETE_POSITION, 'aW'),
        new Token(Type.ATHLETE_BIB, '439'),
        new Token(Type.ATHLETE_FULL_NAME, 'Puglesi Gianluca'),
        new Token(Type.ATHLETE_YOB, '1996'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Königssteiner LV'),
        new Token(Type.PERFORMANCE, '7,42'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, '7,19'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, '7,42'),
        new Token(Type.ATHLETE_POSITION, 'aW'),
        new Token(Type.ATHLETE_BIB, '1374'),
        new Token(Type.ATHLETE_FULL_NAME, 'Castro-Schauer Carlos'),
        new Token(Type.ATHLETE_YOB, '1994'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Eintracht Frankfurt'),
        new Token(Type.PERFORMANCE, '7,19'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, '6,95'),
        new Token(Type.ATTEMPT3, 'x'),
        new Token(Type.ATTEMPT4, '6,95'),
        new Token(Type.ATTEMPT5, '7,12'),
        new Token(Type.ATTEMPT6, '7,19'),
        new Token(Type.END, undefined),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
