import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 12.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/12.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'SLB-Hallenwettkämpfe 2017'),
        new Token(Type.COMPETITION_CITY, 'Saarbrücken'),
        new Token(Type.COMPETITION_VENUE, 'Leichtathletik-Halle'),
        new Token(Type.COMPETITION_START_DATE, '08.01.2017'),
        new Token(Type.DISCIPLINE_NAME, '60m'),
        new Token(Type.AGE_GROUP_NAME, 'Weibliche Jugend U16'),
        new Token(Type.EVENT_DATE, '08.01.2017'),
        new Token(Type.EVENT_TIME, '14:00'),
        new Token(Type.ROUND_NAME, 'Finale'),
        new Token(Type.ATHLETE_BIB, '971'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hessedenz Mascha'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Saarwellingen'),
        new Token(Type.PERFORMANCE, 'ogV'),
        new Token(Type.ATHLETE_BIB, '779'),
        new Token(Type.ATHLETE_FULL_NAME, 'Blug Marthalotte'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Zweibrücken'),
        new Token(Type.PERFORMANCE, 'ogV'),
        new Token(Type.ATHLETE_BIB, '778'),
        new Token(Type.ATHLETE_FULL_NAME, 'Fritzke Lisa'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Zweibrücken'),
        new Token(Type.PERFORMANCE, 'ogV'),
        new Token(Type.ATHLETE_BIB, '777'),
        new Token(Type.ATHLETE_FULL_NAME, 'Boegem Emilie'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Zweibrücken'),
        new Token(Type.PERFORMANCE, 'ogV'),
        new Token(Type.ATHLETE_BIB, '789'),
        new Token(Type.ATHLETE_FULL_NAME, 'Beyerlein Ines'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Zweibrücken'),
        new Token(Type.PERFORMANCE, 'ogV'),
        new Token(Type.ATHLETE_BIB, '908'),
        new Token(Type.ATHLETE_FULL_NAME, 'Waschke Lavinia'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, 'ogV'),
        new Token(Type.ATHLETE_BIB, '968'),
        new Token(Type.ATHLETE_FULL_NAME, 'Rong Alexandra'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Nussdorf'),
        new Token(Type.PERFORMANCE, 'ogV'),
        new Token(Type.ATHLETE_BIB, '802'),
        new Token(Type.ATHLETE_FULL_NAME, 'Stickdorn Alexia'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LC Rehlingen'),
        new Token(Type.PERFORMANCE, 'ogV'),
        new Token(Type.ATHLETE_BIB, '801'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schnubel Dienne'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LC Rehlingen'),
        new Token(Type.PERFORMANCE, 'ogV'),
        new Token(Type.ATHLETE_BIB, '800'),
        new Token(Type.ATHLETE_FULL_NAME, 'Klein Jule'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LC Rehlingen'),
        new Token(Type.PERFORMANCE, 'ogV'),
        new Token(Type.ATHLETE_BIB, '925'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wolffersdorf Johanna'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, 'ogV'),
        new Token(Type.ATHLETE_BIB, '902'),
        new Token(Type.ATHLETE_FULL_NAME, 'Barros Liliana'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, 'ogV'),
        new Token(Type.ATHLETE_BIB, '898'),
        new Token(Type.ATHLETE_FULL_NAME, 'Böning Annabel'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, 'ogV'),
        new Token(Type.ATHLETE_BIB, '792'),
        new Token(Type.ATHLETE_FULL_NAME, 'Passauer Lea'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Zweibrücken'),
        new Token(Type.PERFORMANCE, 'ogV'),
        new Token(Type.ATHLETE_BIB, '979'),
        new Token(Type.ATHLETE_FULL_NAME, 'Lawson-Body Sheila'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Ludweiler'),
        new Token(Type.PERFORMANCE, 'ogV'),
        new Token(Type.DISCIPLINE_NAME, 'Kugelstoß'),
        new Token(Type.AGE_GROUP_NAME, 'Frauen'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '4000g'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '08.01.2017'),
        new Token(Type.EVENT_TIME, '14:15'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '976'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schwarz Desiree'),
        new Token(Type.ATHLETE_YOB, '1992'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, '11,70'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, '11,70'),
        new Token(Type.ATTEMPT3, 'x'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, '11,40'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '937'),
        new Token(Type.ATHLETE_FULL_NAME, 'Bender Britta'),
        new Token(Type.ATHLETE_YOB, '1976'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TuS 1862 Kirn'),
        new Token(Type.PERFORMANCE, '10,97'),
        new Token(Type.ATTEMPT1, '10,61'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, '10,97'),
        new Token(Type.ATTEMPT4, '10,72'),
        new Token(Type.ATTEMPT5, '10,86'),
        new Token(Type.ATTEMPT6, 'x'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '871'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hümke Lara'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LTV Bad Dürkheim'),
        new Token(Type.PERFORMANCE, '10,60'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, '9,45'),
        new Token(Type.ATTEMPT3, '10,53'),
        new Token(Type.ATTEMPT4, '8,57'),
        new Token(Type.ATTEMPT5, '10,30'),
        new Token(Type.ATTEMPT6, '10,60'),
        new Token(Type.ATHLETE_BIB, '739'),
        new Token(Type.ATHLETE_FULL_NAME, 'Will Franziska'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAF Merchweiler'),
        new Token(Type.PERFORMANCE, 'disq.'),
        new Token(Type.COMMENT, 'DLV 7.3 Hochstart in W nicht erlaubt'),
        new Token(Type.END, undefined),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
