import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 13.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/13.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, '33. Nationales Vorweihnachtskriterium'),
        new Token(Type.COMPETITION_CITY, 'Stadtallendorf'),
        new Token(Type.COMPETITION_VENUE, 'Herrenwaldhalle'),
        new Token(Type.COMPETITION_START_DATE, '10.12.2016'),
        new Token(Type.DISCIPLINE_NAME, '60m-Lauf'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend M12'),
        new Token(Type.GROUP_NUMBER, '2'),
        new Token(Type.EVENT_DATE, '11.12.2016'),
        new Token(Type.EVENT_TIME, '09:42'),
        new Token(Type.GROUP_INFO, 'Es qualifizieren sich die 6 Zeitschnellsten (q) für Finale, um 12:20'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '732'),
        new Token(Type.ATHLETE_FULL_NAME, 'Günther Jacob'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV 1912 Niederscheld'),
        new Token(Type.PERFORMANCE, '8,91'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '516'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kroll Lukas'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, '8,93'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '757'),
        new Token(Type.ATHLETE_FULL_NAME, 'Pitz Sören'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Gladenbach'),
        new Token(Type.PERFORMANCE, '9,03'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '347'),
        new Token(Type.ATHLETE_FULL_NAME, 'Strübel Jonas'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Gießen'),
        new Token(Type.PERFORMANCE, '9,31'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '289'),
        new Token(Type.ATHLETE_FULL_NAME, 'Geissel Felix'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'KSV Baunatal'),
        new Token(Type.PERFORMANCE, '9,35'),
        new Token(Type.DISCIPLINE_NAME, '60m-Lauf'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend M12'),
        new Token(Type.GROUP_NUMBER, '3'),
        new Token(Type.EVENT_DATE, '11.12.2016'),
        new Token(Type.EVENT_TIME, '09:44'),
        new Token(Type.GROUP_INFO, 'Es qualifizieren sich die 6 Zeitschnellsten (q) für Finale, um 12:20'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '511'),
        new Token(Type.ATHLETE_FULL_NAME, 'Giesler Noel'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, '9,15'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '735'),
        new Token(Type.ATHLETE_FULL_NAME, 'Graß Jonas'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Bad Schwalbach'),
        new Token(Type.PERFORMANCE, '9,27'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '639'),
        new Token(Type.ATHLETE_FULL_NAME, 'Weber Paul'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Eintracht Stadtallendorf'),
        new Token(Type.PERFORMANCE, '9,83'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '747'),
        new Token(Type.ATHLETE_FULL_NAME, 'Noriega Leandro'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Ewersbach'),
        new Token(Type.PERFORMANCE, '10,15'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '655'),
        new Token(Type.ATHLETE_FULL_NAME, 'Carle Till'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Kirchhain'),
        new Token(Type.PERFORMANCE, '10,27'),
        new Token(Type.DISCIPLINE_NAME, '60m-Lauf'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend M12'),
        new Token(Type.EVENT_DATE, '11.12.2016'),
        new Token(Type.EVENT_TIME, '12:20'),
        new Token(Type.ROUND_NAME, 'Finale'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '465'),
        new Token(Type.ATHLETE_FULL_NAME, 'Siveri Jan'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SC Olpe'),
        new Token(Type.PERFORMANCE, '8,85'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '732'),
        new Token(Type.ATHLETE_FULL_NAME, 'Günther Jacob'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV 1912 Niederscheld'),
        new Token(Type.PERFORMANCE, '8,87'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '653'),
        new Token(Type.ATHLETE_FULL_NAME, 'Eitzenhöfer Jan Luca'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Frankenberg'),
        new Token(Type.PERFORMANCE, '8,87'),
        new Token(Type.GROUP_NUMBER_PLACE, './I'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '757'),
        new Token(Type.ATHLETE_FULL_NAME, 'Pitz Sören'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Gladenbach'),
        new Token(Type.PERFORMANCE, '9,01'),
        new Token(Type.GROUP_NUMBER_PLACE, '4./I'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '516'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kroll Lukas'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, '9,01'),
        new Token(Type.GROUP_NUMBER_PLACE, './I'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '511'),
        new Token(Type.ATHLETE_FULL_NAME, 'Giesler Noel'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, '9,25'),
        new Token(Type.GROUP_NUMBER_PLACE, '6./I'),
        new Token(Type.DISCIPLINE_NAME, '800m-Lauf'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend M12'),
        new Token(Type.EVENT_DATE, '11.12.2016'),
        new Token(Type.EVENT_TIME, '14:30'),
        new Token(Type.ROUND_NAME, 'Zeitläufe'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '762'),
        new Token(Type.ATHLETE_FULL_NAME, 'Muth Elijah'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Hessisch Lichtenau'),
        new Token(Type.PERFORMANCE, '2:31,04'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '395'),
        new Token(Type.ATHLETE_FULL_NAME, 'Koch Elias'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Eder'),
        new Token(Type.PERFORMANCE, '2:32,52'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '349'),
        new Token(Type.ATHLETE_FULL_NAME, 'Will Michael'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Gießen'),
        new Token(Type.PERFORMANCE, '2:36,98'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./I'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '511'),
        new Token(Type.ATHLETE_FULL_NAME, 'Giesler Noel'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, '2:56,14'),
        new Token(Type.GROUP_NUMBER_PLACE, '4./I'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '757'),
        new Token(Type.ATHLETE_FULL_NAME, 'Pitz Sören'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Gladenbach'),
        new Token(Type.PERFORMANCE, '3:01,74'),
        new Token(Type.GROUP_NUMBER_PLACE, '5./I'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '639'),
        new Token(Type.ATHLETE_FULL_NAME, 'Weber Paul'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Eintracht Stadtallendorf'),
        new Token(Type.PERFORMANCE, '3:07,36'),
        new Token(Type.GROUP_NUMBER_PLACE, '6./I'),
        new Token(Type.ATHLETE_POSITION, '7'),
        new Token(Type.ATHLETE_BIB, '747'),
        new Token(Type.ATHLETE_FULL_NAME, 'Noriega Leandro'),
        new Token(Type.ATHLETE_YOB, '2004'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Ewersbach'),
        new Token(Type.PERFORMANCE, '3:13,34'),
        new Token(Type.GROUP_NUMBER_PLACE, '7./I'),
        new Token(Type.END, undefined),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
