import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 14.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/14.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, '33. Nationales Vorweihnachtskriterium'),
        new Token(Type.COMPETITION_CITY, 'Stadtallendorf'),
        new Token(Type.COMPETITION_VENUE, 'Herrenwaldhalle'),
        new Token(Type.COMPETITION_START_DATE, '10.12.2016'),
        new Token(Type.DISCIPLINE_NAME, '800m-Lauf'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W14'),
        new Token(Type.EVENT_DATE, '10.12.2016'),
        new Token(Type.EVENT_TIME, '16:40'),
        new Token(Type.ROUND_NAME, 'Zeitläufe'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '641'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schmidt Gina'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Eintracht Stadtallendorf'),
        new Token(Type.PERFORMANCE, '2:37,54'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '359'),
        new Token(Type.ATHLETE_FULL_NAME, 'Jacobi Luise'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Gießen'),
        new Token(Type.PERFORMANCE, '2:37,94'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '275'),
        new Token(Type.ATHLETE_FULL_NAME, 'Braun Malin'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'GSV Eintracht Baunatal'),
        new Token(Type.PERFORMANCE, '2:38,24'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./I'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '411'),
        new Token(Type.ATHLETE_FULL_NAME, 'Pflüger Elena'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Kaufungen'),
        new Token(Type.PERFORMANCE, '2:38,50'),
        new Token(Type.GROUP_NUMBER_PLACE, '4./I'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '388'),
        new Token(Type.ATHLETE_FULL_NAME, 'Krüger Kaya'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Celle-Land'),
        new Token(Type.PERFORMANCE, '2:39,32'),
        new Token(Type.GROUP_NUMBER_PLACE, '5./I'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '533'),
        new Token(Type.ATHLETE_FULL_NAME, 'Uth Linn-Marit'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SV Lindenau 1848'),
        new Token(Type.PERFORMANCE, '2:42,42'),
        new Token(Type.GROUP_NUMBER_PLACE, '6./I'),
        new Token(Type.ATHLETE_POSITION, '7'),
        new Token(Type.ATHLETE_BIB, '575'),
        new Token(Type.ATHLETE_FULL_NAME, 'Melzer Johanna'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG Nieder-Erlenbach'),
        new Token(Type.PERFORMANCE, '2:45,72'),
        new Token(Type.GROUP_NUMBER_PLACE, '7./I'),
        new Token(Type.ATHLETE_POSITION, '8'),
        new Token(Type.ATHLETE_BIB, '352'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kröck Celine'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Gießen'),
        new Token(Type.PERFORMANCE, '2:49,06'),
        new Token(Type.GROUP_NUMBER_PLACE, '8./I'),
        new Token(Type.ATHLETE_BIB, '253'),
        new Token(Type.ATHLETE_FULL_NAME, 'Buchhold Saskia'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'FSK Lohfelden'),
        new Token(Type.PERFORMANCE, 'n.a.'),
        new Token(Type.ATHLETE_BIB, '252'),
        new Token(Type.ATHLETE_FULL_NAME, 'Meibert Sarah'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'FSK Lohfelden'),
        new Token(Type.PERFORMANCE, 'n.a.'),
        new Token(Type.DISCIPLINE_NAME, 'Hochsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W14'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '10.12.2016'),
        new Token(Type.EVENT_TIME, '09:30'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '387'),
        new Token(Type.ATHLETE_FULL_NAME, 'Boeijink Esther'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Celle-Land'),
        new Token(Type.PERFORMANCE, '1,51'),
        new Token(Type.HEIGHT, '1,25'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,48'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '1,51'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,54'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '630'),
        new Token(Type.ATHLETE_FULL_NAME, 'Sturm Julia'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Eintracht Stadtallendorf'),
        new Token(Type.PERFORMANCE, '1,51'),
        new Token(Type.HEIGHT, '1,25'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,30'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,48'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,51'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,54'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '359'),
        new Token(Type.ATHLETE_FULL_NAME, 'Jacobi Luise'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Gießen'),
        new Token(Type.PERFORMANCE, '1,48'),
        new Token(Type.HEIGHT, '1,25'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,30'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,48'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,51'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '772'),
        new Token(Type.ATHLETE_FULL_NAME, 'Cramer Friederike'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Waldgirmes'),
        new Token(Type.PERFORMANCE, '1,45'),
        new Token(Type.HEIGHT, '1,25'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,48'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '803'),
        new Token(Type.ATHLETE_FULL_NAME, 'Waldeck Amber'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAV Kassel'),
        new Token(Type.PERFORMANCE, '1,40'),
        new Token(Type.HEIGHT, '1,25'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '604'),
        new Token(Type.ATHLETE_FULL_NAME, 'Zuban Christina'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV 05 Remsfeld'),
        new Token(Type.PERFORMANCE, '1,40'),
        new Token(Type.HEIGHT, '1,25'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '278'),
        new Token(Type.ATHLETE_FULL_NAME, 'Richardson Katja'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Königsteiner LV'),
        new Token(Type.PERFORMANCE, '1,40'),
        new Token(Type.HEIGHT, '1,25'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '8'),
        new Token(Type.ATHLETE_BIB, '411'),
        new Token(Type.ATHLETE_FULL_NAME, 'Pflüger Elena'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Kaufungen'),
        new Token(Type.PERFORMANCE, '1,35'),
        new Token(Type.HEIGHT, '1,25'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '8'),
        new Token(Type.ATHLETE_BIB, '252'),
        new Token(Type.ATHLETE_FULL_NAME, 'Meibert Sarah'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'FSK Lohfelden'),
        new Token(Type.PERFORMANCE, '1,35'),
        new Token(Type.HEIGHT, '1,25'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '10'),
        new Token(Type.ATHLETE_BIB, '641'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schmidt Gina'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Eintracht Stadtallendorf'),
        new Token(Type.PERFORMANCE, '1,35'),
        new Token(Type.HEIGHT, '1,25'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '11'),
        new Token(Type.ATHLETE_BIB, '386'),
        new Token(Type.ATHLETE_FULL_NAME, 'Otte Sina'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Celle-Land'),
        new Token(Type.PERFORMANCE, '1,30'),
        new Token(Type.HEIGHT, '1,25'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.DISCIPLINE_NAME, 'Stabhochsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W14'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '10.12.2016'),
        new Token(Type.EVENT_TIME, '10:00'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '431'),
        new Token(Type.ATHLETE_FULL_NAME, 'Vogel Sarah'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Seligenstadt'),
        new Token(Type.PERFORMANCE, '3,30'),
        new Token(Type.HEIGHT, '1,70'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,80'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,90'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,00'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,10'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,20'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,30'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,40'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,50'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,60'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,70'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,80'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,90'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '3,00'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '3,10'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '3,20'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '3,30'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '3,40'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '3,50'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '508'),
        new Token(Type.ATHLETE_FULL_NAME, 'Reuther Delia'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Bad Sooden-Allendorf'),
        new Token(Type.PERFORMANCE, '2,80'),
        new Token(Type.HEIGHT, '1,70'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,80'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,90'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,00'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,10'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,20'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,30'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,40'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,50'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '2,60'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '2,70'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,80'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,90'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '656'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kothe Johanna'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Kirchhain'),
        new Token(Type.PERFORMANCE, '1,90'),
        new Token(Type.HEIGHT, '1,70'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,80'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,90'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,00'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '507'),
        new Token(Type.ATHLETE_FULL_NAME, 'Dumi Dea-Sara'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Bad Sooden-Allendorf'),
        new Token(Type.PERFORMANCE, '1,90'),
        new Token(Type.HEIGHT, '1,70'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,80'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,90'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,00'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.DISCIPLINE_NAME, 'Weitsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W14'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '10.12.2016'),
        new Token(Type.EVENT_TIME, '11:30'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '207'),
        new Token(Type.ATHLETE_FULL_NAME, 'Boppert Tamina'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Alsfelder SC 96'),
        new Token(Type.PERFORMANCE, '5,27'),
        new Token(Type.ATTEMPT1, '5,27'),
        new Token(Type.ATTEMPT2, '5,24'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, 'x'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '630'),
        new Token(Type.ATHLETE_FULL_NAME, 'Sturm Julia'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Eintracht Stadtallendorf'),
        new Token(Type.PERFORMANCE, '5,16'),
        new Token(Type.ATTEMPT1, '5,04'),
        new Token(Type.ATTEMPT2, '4,89'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATTEMPT4, '-'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, '5,16'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '409'),
        new Token(Type.ATHLETE_FULL_NAME, 'Arnold Vivian'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Eintracht Frankfurt'),
        new Token(Type.PERFORMANCE, '4,99'),
        new Token(Type.ATTEMPT1, '4,90'),
        new Token(Type.ATTEMPT2, '4,87'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATTEMPT4, '4,99'),
        new Token(Type.ATTEMPT5, '4,56'),
        new Token(Type.ATTEMPT6, '4,80'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '533'),
        new Token(Type.ATHLETE_FULL_NAME, 'Uth Linn-Marit'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SV Lindenau 1848'),
        new Token(Type.PERFORMANCE, '4,97'),
        new Token(Type.ATTEMPT1, '4,97'),
        new Token(Type.ATTEMPT2, '4,73'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATTEMPT4, '-'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, '4,66'),
        new Token(Type.END, undefined),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
