import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 15.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/15.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'Kreismeisterschaften 2016'),
        new Token(Type.COMPETITION_CITY, 'Marburg'),
        new Token(Type.COMPETITION_VENUE, 'Marburg'),
        new Token(Type.COMPETITION_START_DATE, '17.09.2016'),
        new Token(Type.DISCIPLINE_NAME, 'Fünfkampf'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.EVENT_DATE, '17.09.2016'),
        new Token(Type.PARTICIPANT_COUNT, '1'),
        new Token(Type.ROUND_NAME, 'Finalstand'),
        new Token(Type.COMBINED_DISCIPLINE, '100'),
        new Token(Type.COMBINED_DISCIPLINE, 'WEI'),
        new Token(Type.COMBINED_DISCIPLINE, 'KUG'),
        new Token(Type.COMBINED_DISCIPLINE, 'HOC'),
        new Token(Type.COMBINED_DISCIPLINE, '400'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '155'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kunkel Luca'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Alheimer Rotenburg-Bebra'),
        new Token(Type.PERFORMANCE, '2.813'),
        new Token(Type.COMBINED_PERFORMANCE, '12,33', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '6,21', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '10,19', 'KUG'),
        new Token(Type.COMBINED_PERFORMANCE, '1,70', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '55,64', '400'),
        new Token(Type.COMBINED_WIND, '0,0', '100'),
        new Token(Type.COMBINED_POINTS, '557', '100'),
        new Token(Type.COMBINED_POINTS, '612', 'WEI'),
        new Token(Type.COMBINED_POINTS, '477', 'KUG'),
        new Token(Type.COMBINED_POINTS, '578', 'HOC'),
        new Token(Type.COMBINED_POINTS, '589', '400'),
        new Token(Type.COMBINED_SUM, '557', '100'),
        new Token(Type.COMBINED_SUM, '1.169', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.646', 'KUG'),
        new Token(Type.COMBINED_SUM, '2.224', 'HOC'),
        new Token(Type.COMBINED_SUM, '2.813', '400'),
        new Token(Type.DISCIPLINE_NAME, 'Vierkampf'),
        new Token(Type.AGE_GROUP_NAME, 'Weibliche Jugend U18'),
        new Token(Type.EVENT_DATE, '17.09.2016'),
        new Token(Type.PARTICIPANT_COUNT, '1'),
        new Token(Type.ROUND_NAME, 'Finalstand'),
        new Token(Type.COMBINED_DISCIPLINE, '100'),
        new Token(Type.COMBINED_DISCIPLINE, '10H'),
        new Token(Type.COMBINED_DISCIPLINE, 'HOC'),
        new Token(Type.COMBINED_DISCIPLINE, 'KUG'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '175'),
        new Token(Type.ATHLETE_FULL_NAME, 'Weigel Laura'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_CLUB_NAME, 'ASC 1990 Breidenbach'),
        new Token(Type.PERFORMANCE, '1.724'),
        new Token(Type.COMBINED_PERFORMANCE, '14,86', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '18,87', '10H'),
        new Token(Type.COMBINED_PERFORMANCE, '1,45', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '8,93', 'KUG'),
        new Token(Type.COMBINED_WIND, '0,0', '100'),
        new Token(Type.COMBINED_WIND, '0,0', '10H'),
        new Token(Type.COMBINED_POINTS, '415', '100'),
        new Token(Type.COMBINED_POINTS, '405', '10H'),
        new Token(Type.COMBINED_POINTS, '475', 'HOC'),
        new Token(Type.COMBINED_POINTS, '429', 'KUG'),
        new Token(Type.COMBINED_SUM, '415', '100'),
        new Token(Type.COMBINED_SUM, '820', '10H'),
        new Token(Type.COMBINED_SUM, '1.295', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.724', 'KUG'),
        new Token(Type.DISCIPLINE_NAME, 'Vierkampf'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend M14'),
        new Token(Type.EVENT_DATE, '17.09.2016'),
        new Token(Type.PARTICIPANT_COUNT, '1'),
        new Token(Type.ROUND_NAME, 'Finalstand'),
        new Token(Type.COMBINED_DISCIPLINE, '100'),
        new Token(Type.COMBINED_DISCIPLINE, 'WEI'),
        new Token(Type.COMBINED_DISCIPLINE, 'KUG'),
        new Token(Type.COMBINED_DISCIPLINE, 'HOC'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '152'),
        new Token(Type.ATHLETE_FULL_NAME, 'Stremel Ben'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'FV Wallau'),
        new Token(Type.PERFORMANCE, '1.714'),
        new Token(Type.COMBINED_PERFORMANCE, '14,33', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '4,44', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '7,49', 'KUG'),
        new Token(Type.COMBINED_PERFORMANCE, '1,61', 'HOC'),
        new Token(Type.COMBINED_WIND, '0,0', '100'),
        new Token(Type.COMBINED_POINTS, '390', '100'),
        new Token(Type.COMBINED_POINTS, '436', 'WEI'),
        new Token(Type.COMBINED_POINTS, '354', 'KUG'),
        new Token(Type.COMBINED_POINTS, '534', 'HOC'),
        new Token(Type.COMBINED_SUM, '390', '100'),
        new Token(Type.COMBINED_SUM, '826', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.180', 'KUG'),
        new Token(Type.COMBINED_SUM, '1.714', 'HOC'),
        new Token(Type.DISCIPLINE_NAME, 'Vierkampf'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W15'),
        new Token(Type.EVENT_DATE, '17.09.2016'),
        new Token(Type.PARTICIPANT_COUNT, '1'),
        new Token(Type.ROUND_NAME, 'Finalstand'),
        new Token(Type.COMBINED_DISCIPLINE, '100'),
        new Token(Type.COMBINED_DISCIPLINE, 'WEI'),
        new Token(Type.COMBINED_DISCIPLINE, 'HOC'),
        new Token(Type.COMBINED_DISCIPLINE, 'KUG'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '122'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hausmann Alina'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Eintracht Stadtallendorf'),
        new Token(Type.PERFORMANCE, '1.708'),
        new Token(Type.COMBINED_PERFORMANCE, '14,28', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '4,13', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,45', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '6,65', 'KUG'),
        new Token(Type.COMBINED_WIND, '0,0', '100'),
        new Token(Type.COMBINED_WIND, '-0,2', 'WEI'),
        new Token(Type.COMBINED_POINTS, '456', '100'),
        new Token(Type.COMBINED_POINTS, '451', 'WEI'),
        new Token(Type.COMBINED_POINTS, '475', 'HOC'),
        new Token(Type.COMBINED_POINTS, '326', 'KUG'),
        new Token(Type.COMBINED_SUM, '456', '100'),
        new Token(Type.COMBINED_SUM, '907', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.382', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.708', 'KUG'),
        new Token(Type.DISCIPLINE_NAME, 'Vierkampf'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W14'),
        new Token(Type.EVENT_DATE, '17.09.2016'),
        new Token(Type.PARTICIPANT_COUNT, '1'),
        new Token(Type.ROUND_NAME, 'Finalstand'),
        new Token(Type.COMBINED_DISCIPLINE, '100'),
        new Token(Type.COMBINED_DISCIPLINE, 'WEI'),
        new Token(Type.COMBINED_DISCIPLINE, 'HOC'),
        new Token(Type.COMBINED_DISCIPLINE, 'KUG'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '120'),
        new Token(Type.ATHLETE_FULL_NAME, 'Sturm Julia'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Eintracht Stadtallendorf'),
        new Token(Type.PERFORMANCE, '1.822'),
        new Token(Type.COMBINED_PERFORMANCE, '13,56', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '4,52', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,45', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '6,89', 'KUG'),
        new Token(Type.COMBINED_WIND, '0,0', '100'),
        new Token(Type.COMBINED_POINTS, '513', '100'),
        new Token(Type.COMBINED_POINTS, '496', 'WEI'),
        new Token(Type.COMBINED_POINTS, '475', 'HOC'),
        new Token(Type.COMBINED_POINTS, '338', 'KUG'),
        new Token(Type.COMBINED_SUM, '513', '100'),
        new Token(Type.COMBINED_SUM, '1.009', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.484', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.822', 'KUG'),
        new Token(Type.DISCIPLINE_NAME, 'Vierkampf'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W13'),
        new Token(Type.EVENT_DATE, '17.09.2016'),
        new Token(Type.PARTICIPANT_COUNT, '2'),
        new Token(Type.ROUND_NAME, 'Finalstand'),
        new Token(Type.COMBINED_DISCIPLINE, '75M'),
        new Token(Type.COMBINED_DISCIPLINE, 'WEI'),
        new Token(Type.COMBINED_DISCIPLINE, 'HOC'),
        new Token(Type.COMBINED_DISCIPLINE, 'BAL'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '176'),
        new Token(Type.ATHLETE_FULL_NAME, 'Joedt Sarah'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_CLUB_NAME, 'ASC 1990 Breidenbach'),
        new Token(Type.PERFORMANCE, '1.960'),
        new Token(Type.COMBINED_PERFORMANCE, '10,08', '75M'),
        new Token(Type.COMBINED_PERFORMANCE, '4,91', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,43', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '35,50', 'BAL'),
        new Token(Type.COMBINED_POINTS, '521', '75M'),
        new Token(Type.COMBINED_POINTS, '539', 'WEI'),
        new Token(Type.COMBINED_POINTS, '463', 'HOC'),
        new Token(Type.COMBINED_POINTS, '437', 'BAL'),
        new Token(Type.COMBINED_SUM, '521', '75M'),
        new Token(Type.COMBINED_SUM, '1.060', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.523', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.960', 'BAL'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '119'),
        new Token(Type.ATHLETE_FULL_NAME, 'Erdil Nilay'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Eintracht Stadtallendorf'),
        new Token(Type.PERFORMANCE, '1.653'),
        new Token(Type.COMBINED_PERFORMANCE, '11,44', '75M'),
        new Token(Type.COMBINED_PERFORMANCE, '4,26', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,31', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '32,50', 'BAL'),
        new Token(Type.COMBINED_POINTS, '387', '75M'),
        new Token(Type.COMBINED_POINTS, '466', 'WEI'),
        new Token(Type.COMBINED_POINTS, '388', 'HOC'),
        new Token(Type.COMBINED_POINTS, '412', 'BAL'),
        new Token(Type.COMBINED_SUM, '387', '75M'),
        new Token(Type.COMBINED_SUM, '853', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.241', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.653', 'BAL'),
        new Token(Type.DISCIPLINE_NAME, 'Dreikampf'),
        new Token(Type.AGE_GROUP_NAME, 'Kinder M11'),
        new Token(Type.EVENT_DATE, '17.09.2016'),
        new Token(Type.PARTICIPANT_COUNT, '3'),
        new Token(Type.ROUND_NAME, 'Finalstand'),
        new Token(Type.COMBINED_DISCIPLINE, '50M'),
        new Token(Type.COMBINED_DISCIPLINE, 'WEZ'),
        new Token(Type.COMBINED_DISCIPLINE, 'SCH'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '148'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hannich Linus-Ben'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'FV Wallau'),
        new Token(Type.PERFORMANCE, '937'),
        new Token(Type.COMBINED_PERFORMANCE, '8,69', '50M'),
        new Token(Type.COMBINED_PERFORMANCE, '3,72', 'WEZ'),
        new Token(Type.COMBINED_PERFORMANCE, '37,00', 'SCH'),
        new Token(Type.COMBINED_POINTS, '284', '50M'),
        new Token(Type.COMBINED_POINTS, '355', 'WEZ'),
        new Token(Type.COMBINED_POINTS, '298', 'SCH'),
        new Token(Type.COMBINED_SUM, '284', '50M'),
        new Token(Type.COMBINED_SUM, '639', 'WEZ'),
        new Token(Type.COMBINED_SUM, '937', 'SCH'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '144'),
        new Token(Type.ATHLETE_FULL_NAME, 'Dönges Christian'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Gladenbach'),
        new Token(Type.PERFORMANCE, '921'),
        new Token(Type.COMBINED_PERFORMANCE, '8,41', '50M'),
        new Token(Type.COMBINED_PERFORMANCE, '3,68', 'WEZ'),
        new Token(Type.COMBINED_PERFORMANCE, '32,00', 'SCH'),
        new Token(Type.COMBINED_POINTS, '312', '50M'),
        new Token(Type.COMBINED_POINTS, '350', 'WEZ'),
        new Token(Type.COMBINED_POINTS, '259', 'SCH'),
        new Token(Type.COMBINED_SUM, '312', '50M'),
        new Token(Type.COMBINED_SUM, '662', 'WEZ'),
        new Token(Type.COMBINED_SUM, '921', 'SCH'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '173'),
        new Token(Type.ATHLETE_FULL_NAME, 'Gisse Nico'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'ASC 1990 Breidenbach'),
        new Token(Type.PERFORMANCE, '850'),
        new Token(Type.COMBINED_PERFORMANCE, '8,65', '50M'),
        new Token(Type.COMBINED_PERFORMANCE, '3,39', 'WEZ'),
        new Token(Type.COMBINED_PERFORMANCE, '30,50', 'SCH'),
        new Token(Type.COMBINED_POINTS, '288', '50M'),
        new Token(Type.COMBINED_POINTS, '315', 'WEZ'),
        new Token(Type.COMBINED_POINTS, '247', 'SCH'),
        new Token(Type.COMBINED_SUM, '288', '50M'),
        new Token(Type.COMBINED_SUM, '603', 'WEZ'),
        new Token(Type.COMBINED_SUM, '850', 'SCH'),
        new Token(Type.DISCIPLINE_NAME, 'Vierkampf'),
        new Token(Type.AGE_GROUP_NAME, 'Kinder M11'),
        new Token(Type.EVENT_DATE, '17.09.2016'),
        new Token(Type.PARTICIPANT_COUNT, '3'),
        new Token(Type.ROUND_NAME, 'Finalstand'),
        new Token(Type.COMBINED_DISCIPLINE, '50M'),
        new Token(Type.COMBINED_DISCIPLINE, 'WEZ'),
        new Token(Type.COMBINED_DISCIPLINE, 'HOC'),
        new Token(Type.COMBINED_DISCIPLINE, 'SCH'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '143'),
        new Token(Type.ATHLETE_FULL_NAME, 'Löscher Thomas'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Gladenbach'),
        new Token(Type.PERFORMANCE, '1.252'),
        new Token(Type.COMBINED_PERFORMANCE, '8,37', '50M'),
        new Token(Type.COMBINED_PERFORMANCE, '3,79', 'WEZ'),
        new Token(Type.COMBINED_PERFORMANCE, '1,18', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '33,00', 'SCH'),
        new Token(Type.COMBINED_POINTS, '316', '50M'),
        new Token(Type.COMBINED_POINTS, '363', 'WEZ'),
        new Token(Type.COMBINED_POINTS, '306', 'HOC'),
        new Token(Type.COMBINED_POINTS, '267', 'SCH'),
        new Token(Type.COMBINED_SUM, '316', '50M'),
        new Token(Type.COMBINED_SUM, '679', 'WEZ'),
        new Token(Type.COMBINED_SUM, '985', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.252', 'SCH'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '182'),
        new Token(Type.ATHLETE_FULL_NAME, 'Gärtner Jascha'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'ASC 1990 Breidenbach'),
        new Token(Type.PERFORMANCE, '1.251'),
        new Token(Type.COMBINED_PERFORMANCE, '8,25', '50M'),
        new Token(Type.COMBINED_PERFORMANCE, '3,87', 'WEZ'),
        new Token(Type.COMBINED_PERFORMANCE, '1,21', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '28,00', 'SCH'),
        new Token(Type.COMBINED_POINTS, '329', '50M'),
        new Token(Type.COMBINED_POINTS, '373', 'WEZ'),
        new Token(Type.COMBINED_POINTS, '323', 'HOC'),
        new Token(Type.COMBINED_POINTS, '226', 'SCH'),
        new Token(Type.COMBINED_SUM, '329', '50M'),
        new Token(Type.COMBINED_SUM, '702', 'WEZ'),
        new Token(Type.COMBINED_SUM, '1.025', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.251', 'SCH'),
        new Token(Type.END, undefined),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
