import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 19.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/19.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'Werfertag'),
        new Token(Type.COMPETITION_CITY, 'Dietzhölztal'),
        new Token(Type.COMPETITION_VENUE, 'Ewersbach'),
        new Token(Type.COMPETITION_START_DATE, '24.09.2016'),
        new Token(Type.DISCIPLINE_NAME, 'Kugelstoß (W5K)'),
        new Token(Type.AGE_GROUP_NAME, 'Männer'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '7260g'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '06.08.2016'),
        new Token(Type.EVENT_TIME, '17:00'),
        new Token(Type.ATHLETE_POSITION, '1 (3)'),
        new Token(Type.ATHLETE_BIB, '59'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hofmann Dominik'),
        new Token(Type.ATHLETE_YOB, '1990'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSF Heuchelheim'),
        new Token(Type.RESULT_WEIGHT, '7260g'),
        new Token(Type.PERFORMANCE, '10,87'),
        new Token(Type.ATTEMPT1, '10,03'),
        new Token(Type.ATTEMPT2, '10,68'),
        new Token(Type.ATTEMPT3, '10,87'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, '9,91'),
        new Token(Type.ATTEMPT6, '10,47'),
        new Token(Type.DISCIPLINE_NAME, 'Diskuswurf (W5K)'),
        new Token(Type.AGE_GROUP_NAME, 'Männer'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '2000g'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '06.08.2016'),
        new Token(Type.EVENT_TIME, '14:15'),
        new Token(Type.ATHLETE_POSITION, '1 (1)'),
        new Token(Type.ATHLETE_BIB, '59'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hofmann Dominik'),
        new Token(Type.ATHLETE_YOB, '1990'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSF Heuchelheim'),
        new Token(Type.RESULT_WEIGHT, '2000g'),
        new Token(Type.PERFORMANCE, '35,47'),
        new Token(Type.ATTEMPT1, '35,47'),
        new Token(Type.ATTEMPT2, '-'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATTEMPT4, '-'),
        new Token(Type.ATTEMPT5, '-'),
        new Token(Type.ATTEMPT6, '-'),
        new Token(Type.DISCIPLINE_NAME, 'Hammerwurf (W5K)'),
        new Token(Type.AGE_GROUP_NAME, 'Männer'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '7260g'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '06.08.2016'),
        new Token(Type.EVENT_TIME, '11:30'),
        new Token(Type.ATHLETE_POSITION, '1 (1)'),
        new Token(Type.ATHLETE_BIB, '26'),
        new Token(Type.ATHLETE_FULL_NAME, 'Martin Sebastian'),
        new Token(Type.ATHLETE_YOB, '1994'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Elz'),
        new Token(Type.RESULT_WEIGHT, '7260g'),
        new Token(Type.PERFORMANCE, '54,90'),
        new Token(Type.ATTEMPT1, '-'),
        new Token(Type.ATTEMPT2, '-'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATTEMPT4, '54,90'),
        new Token(Type.ATTEMPT5, '-'),
        new Token(Type.ATTEMPT6, '-'),
        new Token(Type.ATHLETE_POSITION, '2 (2)'),
        new Token(Type.ATHLETE_BIB, '25'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schüssler Peter'),
        new Token(Type.ATHLETE_YOB, '1989'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Elz'),
        new Token(Type.RESULT_WEIGHT, '7260g'),
        new Token(Type.PERFORMANCE, '46,11'),
        new Token(Type.ATTEMPT1, '-'),
        new Token(Type.ATTEMPT2, '45,42'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATTEMPT4, '45,30'),
        new Token(Type.ATTEMPT5, '-'),
        new Token(Type.ATTEMPT6, '46,11'),
        new Token(Type.DISCIPLINE_NAME, 'Kugelstoß (W5K)'),
        new Token(Type.AGE_GROUP_NAME, 'Frauen'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '4000g'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '06.08.2016'),
        new Token(Type.EVENT_TIME, '14:15'),
        new Token(Type.ATHLETE_BIB, '32'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wallisch Vanessa'),
        new Token(Type.ATHLETE_YOB, '1993'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG Wehrheim'),
        new Token(Type.PERFORMANCE, 'n.a.'),
        new Token(Type.DISCIPLINE_NAME, 'Diskuswurf (W5K)'),
        new Token(Type.AGE_GROUP_NAME, 'Frauen'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '1000g'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '06.08.2016'),
        new Token(Type.EVENT_TIME, '15:30'),
        new Token(Type.ATHLETE_BIB, '32'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wallisch Vanessa'),
        new Token(Type.ATHLETE_YOB, '1993'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG Wehrheim'),
        new Token(Type.PERFORMANCE, 'n.a.'),
        new Token(Type.DISCIPLINE_NAME, 'Hammerwurf (W5K)'),
        new Token(Type.AGE_GROUP_NAME, 'Frauen'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '4000g'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '06.08.2016'),
        new Token(Type.EVENT_TIME, '12:15'),
        new Token(Type.ATHLETE_POSITION, '1 (1)'),
        new Token(Type.ATHLETE_BIB, '6'),
        new Token(Type.ATHLETE_FULL_NAME, 'Genz Alina'),
        new Token(Type.ATHLETE_YOB, '1992'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Stadtallendorf'),
        new Token(Type.RESULT_WEIGHT, '4000g'),
        new Token(Type.PERFORMANCE, '47,97'),
        new Token(Type.ATTEMPT1, '-'),
        new Token(Type.ATTEMPT2, '45,05'),
        new Token(Type.ATTEMPT3, '47,97'),
        new Token(Type.ATTEMPT4, '-'),
        new Token(Type.ATTEMPT5, '46,68'),
        new Token(Type.ATTEMPT6, '47,92'),
        new Token(Type.ATHLETE_BIB, '32'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wallisch Vanessa'),
        new Token(Type.ATHLETE_YOB, '1993'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG Wehrheim'),
        new Token(Type.PERFORMANCE, 'n.a.'),
        new Token(Type.ATTEMPT1, '36,80'),
        new Token(Type.ATTEMPT2, '-'),
        new Token(Type.ATTEMPT3, '35,10'),
        new Token(Type.ATTEMPT4, '38,25'),
        new Token(Type.ATTEMPT5, '34,52'),
        new Token(Type.ATTEMPT6, '23,88'),
        new Token(Type.DISCIPLINE_NAME, 'Hammerwurf (W5K)'),
        new Token(Type.AGE_GROUP_NAME, 'Frauen'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '4000g'),
        new Token(Type.GROUP_NUMBER, '2'),
        new Token(Type.EVENT_DATE, '06.08.2016'),
        new Token(Type.EVENT_TIME, '12:17'),
        new Token(Type.DISCIPLINE_NAME, 'Kugelstoß (W5K)'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U20'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '6000g'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '06.08.2016'),
        new Token(Type.EVENT_TIME, '17:00'),
        new Token(Type.ATHLETE_BIB, '15'),
        new Token(Type.ATHLETE_FULL_NAME, 'Bender Moritz'),
        new Token(Type.ATHLETE_YOB, '1997'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSF Heuchelheim'),
        new Token(Type.PERFORMANCE, 'n.a.'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
