import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 2.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/2.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'Kreiseinzelmeisterschaften'),
        new Token(Type.COMPETITION_CITY, 'Coesfeld'),
        new Token(Type.COMPETITION_VENUE, 'Coesfeld'),
        new Token(Type.COMPETITION_START_DATE, '17.09.2016'),
        new Token(Type.DISCIPLINE_NAME, '400m'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.EVENT_DATE, '17.09.2016'),
        new Token(Type.EVENT_TIME, '18:30'),
        new Token(Type.ROUND_NAME, 'Zeitläufe'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '2247'),
        new Token(Type.ATHLETE_FULL_NAME, 'Darpe Janik'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Ems Warendorf'),
        new Token(Type.PERFORMANCE, '56,98'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '147'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kassebeer Jens'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LSF Münster'),
        new Token(Type.PERFORMANCE, '58,69'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '2246'),
        new Token(Type.ATHLETE_FULL_NAME, 'Höft Jacob'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Ems Warendorf'),
        new Token(Type.PERFORMANCE, '62,79'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./I'),
        new Token(Type.DISCIPLINE_NAME, '800m'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.EVENT_DATE, '17.09.2016'),
        new Token(Type.EVENT_TIME, '18:00'),
        new Token(Type.ROUND_NAME, 'Zeitläufe'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '145'),
        new Token(Type.ATHLETE_FULL_NAME, 'Niehues Sebastian'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'VfL Kamen'),
        new Token(Type.PERFORMANCE, '2:03,94'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '2187'),
        new Token(Type.ATHLETE_FULL_NAME, 'Martschei Sebastian'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Coesfeld'),
        new Token(Type.PERFORMANCE, '2:19,31'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '2450'),
        new Token(Type.ATHLETE_FULL_NAME, 'Woltering Felix'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG Dülmen'),
        new Token(Type.PERFORMANCE, '2:40,48'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./I'),
        new Token(Type.ATHLETE_BIB, '2483'),
        new Token(Type.ATHLETE_FULL_NAME, 'Oing Sebastian'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Westfalia Epe'),
        new Token(Type.PERFORMANCE, 'n.a.'),
        new Token(Type.DISCIPLINE_NAME, '110m Hürden'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '914mm'),
        new Token(Type.EVENT_DATE, '17.09.2016'),
        new Token(Type.EVENT_TIME, '15:50'),
        new Token(Type.ROUND_NAME, 'Zeitläufe'),
        new Token(Type.WIND, 'I:+0,4'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '2434'),
        new Token(Type.ATHLETE_FULL_NAME, 'Jahn Lennart'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TLV Germania Überruhr'),
        new Token(Type.PERFORMANCE, '15,74'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '2148'),
        new Token(Type.ATHLETE_FULL_NAME, 'Büning Adrian'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Leichtathletik Nütterden'),
        new Token(Type.PERFORMANCE, '16,62'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '2247'),
        new Token(Type.ATHLETE_FULL_NAME, 'Darpe Janik'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Ems Warendorf'),
        new Token(Type.PERFORMANCE, '16,67'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./I'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '2449'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hornig Florian'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG Dülmen'),
        new Token(Type.PERFORMANCE, '17,31'),
        new Token(Type.GROUP_NUMBER_PLACE, '4./I'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '2450'),
        new Token(Type.ATHLETE_FULL_NAME, 'Woltering Felix'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG Dülmen'),
        new Token(Type.PERFORMANCE, '20,75'),
        new Token(Type.GROUP_NUMBER_PLACE, '5./I'),
        new Token(Type.DISCIPLINE_NAME, 'Hochsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '17.09.2016'),
        new Token(Type.EVENT_TIME, '13:10'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '2449'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hornig Florian'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG Dülmen'),
        new Token(Type.PERFORMANCE, '1,81'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,50'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,55'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,60'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,63'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,66'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,69'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,72'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,75'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,78'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,81'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '1,84'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '2181'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hörnemann Malte'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Coesfeld'),
        new Token(Type.PERFORMANCE, '1,55'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,50'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,55'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '1,60'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.DISCIPLINE_NAME, 'Weitsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '17.09.2016'),
        new Token(Type.EVENT_TIME, '11:00'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '2291'),
        new Token(Type.ATHLETE_FULL_NAME, 'Dabrowski Simon'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SC Union 08 Lüdinghausen'),
        new Token(Type.PERFORMANCE, '5,75'),
        new Token(Type.WIND, '+0,1'),
        new Token(Type.ATTEMPT1, '5,56'),
        new Token(Type.ATTEMPT2, '5,75'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATTEMPT4, '5,50'),
        new Token(Type.ATTEMPT5, '-'),
        new Token(Type.ATTEMPT6, '-'),
        new Token(Type.ATTEMPT_WIND1, '+0,5'),
        new Token(Type.ATTEMPT_WIND2, '+0,1'),
        new Token(Type.ATTEMPT_WIND4, '+0,6'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '2449'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hornig Florian'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG Dülmen'),
        new Token(Type.PERFORMANCE, '5,67'),
        new Token(Type.WIND, '+0,1'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, '5,67'),
        new Token(Type.ATTEMPT4, '5,61'),
        new Token(Type.ATTEMPT5, '5,61'),
        new Token(Type.ATTEMPT6, '5,51'),
        new Token(Type.ATTEMPT_WIND1, '+0,1'),
        new Token(Type.ATTEMPT_WIND2, '0,0'),
        new Token(Type.ATTEMPT_WIND3, '+0,1'),
        new Token(Type.ATTEMPT_WIND4, '+0,7'),
        new Token(Type.ATTEMPT_WIND5, '+0,4'),
        new Token(Type.ATTEMPT_WIND6, '+0,3'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '2149'),
        new Token(Type.ATHLETE_FULL_NAME, 'Knapp Stefan'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Coesfeld'),
        new Token(Type.PERFORMANCE, '5,64'),
        new Token(Type.WIND, '-0,1'),
        new Token(Type.ATTEMPT1, '5,23'),
        new Token(Type.ATTEMPT2, '5,30'),
        new Token(Type.ATTEMPT3, '5,41'),
        new Token(Type.ATTEMPT4, '5,45'),
        new Token(Type.ATTEMPT5, '5,42'),
        new Token(Type.ATTEMPT6, '5,64'),
        new Token(Type.ATTEMPT_WIND1, '+1,0'),
        new Token(Type.ATTEMPT_WIND2, '+0,2'),
        new Token(Type.ATTEMPT_WIND3, '0,0'),
        new Token(Type.ATTEMPT_WIND4, '+0,3'),
        new Token(Type.ATTEMPT_WIND5, '-0,6'),
        new Token(Type.ATTEMPT_WIND6, '-0,1'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '2187'),
        new Token(Type.ATHLETE_FULL_NAME, 'Martschei Sebastian'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Coesfeld'),
        new Token(Type.PERFORMANCE, '5,43'),
        new Token(Type.WIND, '0,0'),
        new Token(Type.ATTEMPT1, '5,23'),
        new Token(Type.ATTEMPT2, '5,20'),
        new Token(Type.ATTEMPT3, '5,43'),
        new Token(Type.ATTEMPT4, '-'),
        new Token(Type.ATTEMPT5, '5,28'),
        new Token(Type.ATTEMPT6, '-'),
        new Token(Type.ATTEMPT_WIND1, '+0,4'),
        new Token(Type.ATTEMPT_WIND2, '+0,1'),
        new Token(Type.ATTEMPT_WIND3, '0,0'),
        new Token(Type.ATTEMPT_WIND5, '+0,2'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
