import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 21.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/21.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'Nordhessische Hallenmeisterschaft'),
        new Token(Type.COMPETITION_CITY, 'Bad Sooden-Allendorf'),
        new Token(Type.COMPETITION_VENUE, 'Eilse-Sporthalle Bad Sooden-Allendorf'),
        new Token(Type.COMPETITION_START_DATE, '29.01.2017'),
        new Token(Type.DISCIPLINE_NAME, 'Weitsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '13:15'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '17'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kunkel Luca'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Alheimer/Rotenburg-Bebra'),
        new Token(Type.PERFORMANCE, '6,47'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, '6,29'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, '6,44'),
        new Token(Type.ATTEMPT6, '6,47'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '106'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hennemuth Philip'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Bad Sooden-Allendorf'),
        new Token(Type.PERFORMANCE, '6,31'),
        new Token(Type.ATTEMPT1, '5,87'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, '5,43'),
        new Token(Type.ATTEMPT4, '6,01'),
        new Token(Type.ATTEMPT5, '6,04'),
        new Token(Type.ATTEMPT6, '6,31'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '28'),
        new Token(Type.ATHLETE_FULL_NAME, 'Umbach Anton'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'ESV Jahn Treysa'),
        new Token(Type.PERFORMANCE, '6,00'),
        new Token(Type.ATTEMPT1, '6,00'),
        new Token(Type.ATTEMPT2, '5,81'),
        new Token(Type.ATTEMPT3, '5,70'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, '5,49'),
        new Token(Type.ATTEMPT6, '5,90'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '75'),
        new Token(Type.ATHLETE_FULL_NAME, 'Eckardt Marten'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAV Kassel'),
        new Token(Type.PERFORMANCE, '5,94'),
        new Token(Type.ATTEMPT1, '5,94'),
        new Token(Type.ATTEMPT2, '5,86'),
        new Token(Type.ATTEMPT3, '5,70'),
        new Token(Type.ATTEMPT4, '5,79'),
        new Token(Type.ATTEMPT5, '5,87'),
        new Token(Type.ATTEMPT6, '5,80'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '7'),
        new Token(Type.ATHLETE_FULL_NAME, 'Eitzenhöfer Jonas'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Hessen 1846 Frankenberg'),
        new Token(Type.PERFORMANCE, '5,90'),
        new Token(Type.ATTEMPT1, '5,50'),
        new Token(Type.ATTEMPT2, '5,65'),
        new Token(Type.ATTEMPT3, '5,53'),
        new Token(Type.ATTEMPT4, '5,75'),
        new Token(Type.ATTEMPT5, '5,68'),
        new Token(Type.ATTEMPT6, '5,90'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '5'),
        new Token(Type.ATHLETE_FULL_NAME, 'Soose David'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'GSV Eintracht Baunatal'),
        new Token(Type.PERFORMANCE, '5,79'),
        new Token(Type.ATTEMPT1, '5,63'),
        new Token(Type.ATTEMPT2, '5,79'),
        new Token(Type.ATTEMPT3, '5,47'),
        new Token(Type.ATTEMPT4, '5,70'),
        new Token(Type.ATTEMPT5, '5,51'),
        new Token(Type.ATTEMPT6, '5,65'),
        new Token(Type.ATHLETE_POSITION, '7'),
        new Token(Type.ATHLETE_BIB, '127'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wahid Muhammad'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, '5,41'),
        new Token(Type.ATTEMPT1, '5,26'),
        new Token(Type.ATTEMPT2, '5,05'),
        new Token(Type.ATTEMPT3, '5,37'),
        new Token(Type.ATTEMPT4, '5,39'),
        new Token(Type.ATTEMPT5, '5,30'),
        new Token(Type.ATTEMPT6, '5,41'),
        new Token(Type.ATHLETE_POSITION, '8'),
        new Token(Type.ATHLETE_BIB, '2'),
        new Token(Type.ATHLETE_FULL_NAME, 'Gerke Julius'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV 09 Twiste'),
        new Token(Type.PERFORMANCE, '5,33'),
        new Token(Type.ATTEMPT1, '5,31'),
        new Token(Type.ATTEMPT2, '5,30'),
        new Token(Type.ATTEMPT3, '5,15'),
        new Token(Type.ATTEMPT4, '5,21'),
        new Token(Type.ATTEMPT5, '5,08'),
        new Token(Type.ATTEMPT6, '5,33'),
        new Token(Type.ATHLETE_POSITION, '9'),
        new Token(Type.ATHLETE_BIB, '12'),
        new Token(Type.ATHLETE_FULL_NAME, 'Trebing Claudius'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TuSpo Borken'),
        new Token(Type.PERFORMANCE, '5,29'),
        new Token(Type.ATTEMPT1, '5,29'),
        new Token(Type.ATTEMPT2, '5,29'),
        new Token(Type.ATTEMPT3, '5,12'),
        new Token(Type.ATTEMPT4, '-'),
        new Token(Type.ATTEMPT5, '-'),
        new Token(Type.ATTEMPT6, '-'),
        new Token(Type.ATHLETE_POSITION, '10'),
        new Token(Type.ATHLETE_BIB, '88'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schade Hendrik'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAV Kassel'),
        new Token(Type.PERFORMANCE, '4,96'),
        new Token(Type.ATTEMPT1, '4,96'),
        new Token(Type.ATTEMPT2, '4,88'),
        new Token(Type.ATTEMPT3, '4,86'),
        new Token(Type.ATTEMPT4, '-'),
        new Token(Type.ATTEMPT5, '-'),
        new Token(Type.ATTEMPT6, '-'),
        new Token(Type.ATHLETE_POSITION, '11'),
        new Token(Type.ATHLETE_BIB, '125'),
        new Token(Type.ATHLETE_FULL_NAME, 'Nowak Leon'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV 05 Remsfeld'),
        new Token(Type.PERFORMANCE, '4,84'),
        new Token(Type.ATTEMPT1, '4,09'),
        new Token(Type.ATTEMPT2, '4,61'),
        new Token(Type.ATTEMPT3, '4,84'),
        new Token(Type.ATHLETE_BIB, '6'),
        new Token(Type.ATHLETE_FULL_NAME, 'Flammann Nic'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'GSV Eintracht Baunatal'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.ATHLETE_BIB, '109'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hempel Pascal'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Bad Sooden-Allendorf'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.ATHLETE_BIB, '62'),
        new Token(Type.ATHLETE_FULL_NAME, 'Dersch Jan-Niklas'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Eder'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.DISCIPLINE_NAME, 'Kugelstoß'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '14:30'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '17'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kunkel Luca'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Alheimer/Rotenburg-Bebra'),
        new Token(Type.PERFORMANCE, '11,86'),
        new Token(Type.ATTEMPT1, '11,81'),
        new Token(Type.ATTEMPT2, '11,86'),
        new Token(Type.ATTEMPT3, '11,37'),
        new Token(Type.ATTEMPT4, '11,58'),
        new Token(Type.ATTEMPT5, '11,50'),
        new Token(Type.ATTEMPT6, '11,43'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '125'),
        new Token(Type.ATHLETE_FULL_NAME, 'Nowak Leon'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV 05 Remsfeld'),
        new Token(Type.PERFORMANCE, '8,59'),
        new Token(Type.ATTEMPT1, '8,59'),
        new Token(Type.ATTEMPT2, '7,26'),
        new Token(Type.ATTEMPT3, '8,15'),
        new Token(Type.ATTEMPT4, '8,50'),
        new Token(Type.ATTEMPT5, '8,54'),
        new Token(Type.ATTEMPT6, 'x'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
