import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 22.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/22.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'Hessische Seniorenmeisterschaften Halle'),
        new Token(Type.COMPETITION_CITY, 'Stadtallendorf'),
        new Token(Type.COMPETITION_VENUE, 'Herrenwaldhalle'),
        new Token(Type.COMPETITION_START_DATE, '12.02.2017'),
        new Token(Type.DISCIPLINE_NAME, '200m'),
        new Token(Type.AGE_GROUP_NAME, 'Senioren M80'),
        new Token(Type.EVENT_DATE, '12.02.2017'),
        new Token(Type.EVENT_TIME, '12:50'),
        new Token(Type.ROUND_NAME, 'Zeitläufe'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '199'),
        new Token(Type.ATHLETE_FULL_NAME, 'Geier Harry'),
        new Token(Type.ATHLETE_YOB, '1935'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'MT Melsungen'),
        new Token(Type.PERFORMANCE, '35,55'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.DISCIPLINE_NAME, '400m'),
        new Token(Type.AGE_GROUP_NAME, 'Senioren M80'),
        new Token(Type.EVENT_DATE, '12.02.2017'),
        new Token(Type.EVENT_TIME, '14:50'),
        new Token(Type.ROUND_NAME, 'Zeitläufe'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '199'),
        new Token(Type.ATHLETE_FULL_NAME, 'Geier Harry'),
        new Token(Type.ATHLETE_YOB, '1935'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'MT Melsungen'),
        new Token(Type.PERFORMANCE, '83,31'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.DISCIPLINE_NAME, 'Hochsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Senioren M80'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '12.02.2017'),
        new Token(Type.EVENT_TIME, '15:05'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '12'),
        new Token(Type.ATHLETE_FULL_NAME, 'Marchlowitz Karl-Heinz'),
        new Token(Type.ATHLETE_YOB, '1937'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Bad Soden/Sulzbach/Neuenhain'),
        new Token(Type.PERFORMANCE, '1,05'),
        new Token(Type.HEIGHT, '0,90'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '0,95'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,00'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,05'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,10'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.DISCIPLINE_NAME, 'Weitsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Senioren M80'),
        new Token(Type.EVENT_DATE, '12.02.2017'),
        new Token(Type.EVENT_TIME, '10:50'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '12'),
        new Token(Type.ATHLETE_FULL_NAME, 'Marchlowitz Karl-Heinz'),
        new Token(Type.ATHLETE_YOB, '1937'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Bad Soden/Sulzbach/Neuenhain'),
        new Token(Type.PERFORMANCE, '2,96'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, '2,70'),
        new Token(Type.ATTEMPT4, '2,96'),
        new Token(Type.ATTEMPT5, '2,95'),
        new Token(Type.ATTEMPT6, '2,81'),
        new Token(Type.DISCIPLINE_NAME, 'Kugelstoß'),
        new Token(Type.AGE_GROUP_NAME, 'Senioren M80'),
        new Token(Type.EVENT_DATE, '12.02.2017'),
        new Token(Type.EVENT_TIME, '14:40'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '188'),
        new Token(Type.ATHLETE_FULL_NAME, 'Siems Erich'),
        new Token(Type.ATHLETE_YOB, '1935'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Main Taunus West'),
        new Token(Type.PERFORMANCE, '10,33'),
        new Token(Type.ATTEMPT1, '9,50'),
        new Token(Type.ATTEMPT2, '10,33'),
        new Token(Type.ATTEMPT3, '9,64'),
        new Token(Type.ATTEMPT4, '10,14'),
        new Token(Type.ATTEMPT5, '9,03'),
        new Token(Type.ATTEMPT6, '10,08'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '131'),
        new Token(Type.ATHLETE_FULL_NAME, 'Janson Heinz'),
        new Token(Type.ATHLETE_YOB, '1937'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Groß-Gerau'),
        new Token(Type.PERFORMANCE, '9,95'),
        new Token(Type.ATTEMPT1, '9,61'),
        new Token(Type.ATTEMPT2, '7,93'),
        new Token(Type.ATTEMPT3, '9,95'),
        new Token(Type.ATTEMPT4, '9,67'),
        new Token(Type.ATTEMPT5, '9,61'),
        new Token(Type.ATTEMPT6, 'x'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '12'),
        new Token(Type.ATHLETE_FULL_NAME, 'Marchlowitz Karl-Heinz'),
        new Token(Type.ATHLETE_YOB, '1937'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Bad Soden/Sulzbach/Neuenhain'),
        new Token(Type.PERFORMANCE, '9,05'),
        new Token(Type.ATTEMPT1, '8,66'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, '8,54'),
        new Token(Type.ATTEMPT4, '9,05'),
        new Token(Type.ATTEMPT5, '-'),
        new Token(Type.ATTEMPT6, '-'),
        new Token(Type.ATHLETE_BIB, '189'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wenig Günther'),
        new Token(Type.ATHLETE_YOB, '1936'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Main Taunus West'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.ATTEMPT1, '-'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
