import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 23.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/23.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'SLB-Hallenwettkämpfe 2017'),
        new Token(Type.COMPETITION_CITY, 'Saarbrücken'),
        new Token(Type.COMPETITION_VENUE, 'Leichtathletik-Halle'),
        new Token(Type.COMPETITION_START_DATE, '08.01.2017'),
        new Token(Type.DISCIPLINE_NAME, '60m'),
        new Token(Type.AGE_GROUP_NAME, 'Frauen'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '08.01.2017'),
        new Token(Type.EVENT_TIME, '13:00'),
        new Token(Type.GROUP_INFO, 'Es qualifizieren sich die 10 Zeitschnellsten (q) für A-/B-Finale, um 14:45'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '946'),
        new Token(Type.ATHLETE_FULL_NAME, 'Donner-Koglin Dunja'),
        new Token(Type.ATHLETE_YOB, '1990'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Dillingen'),
        new Token(Type.PERFORMANCE, '8,35'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.COMMENT, 'Verzicht auf Endlauf'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '733'),
        new Token(Type.ATHLETE_FULL_NAME, 'Gönner Svenja'),
        new Token(Type.ATHLETE_YOB, '1993'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LA Team Saar'),
        new Token(Type.PERFORMANCE, '8,36'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '930'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hochstrate Kirstin'),
        new Token(Type.ATHLETE_YOB, '1970'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TuS 1860 Neunkirchen'),
        new Token(Type.PERFORMANCE, '8,50'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '883'),
        new Token(Type.ATHLETE_FULL_NAME, 'Milseck Aurelie'),
        new Token(Type.ATHLETE_YOB, '1995'),
        new Token(Type.ATHLETE_COUNTRY, 'FRA'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Strasbourg Agglomeration Athletisme S2A'),
        new Token(Type.PERFORMANCE, '8,52'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '884'),
        new Token(Type.ATHLETE_FULL_NAME, 'Sublon Lucille'),
        new Token(Type.ATHLETE_YOB, '1970'),
        new Token(Type.ATHLETE_COUNTRY, 'FRA'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Strasbourg Agglomeration Athletisme S2A'),
        new Token(Type.PERFORMANCE, '9,03'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_BIB, '892'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kletke Vera'),
        new Token(Type.ATHLETE_YOB, '1967'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TG Konz'),
        new Token(Type.PERFORMANCE, 'disq.'),
        new Token(Type.COMMENT, '162 Punkt 6 Fehlstart'),
        new Token(Type.DISCIPLINE_NAME, '60m'),
        new Token(Type.AGE_GROUP_NAME, 'Frauen'),
        new Token(Type.GROUP_NUMBER, '2'),
        new Token(Type.EVENT_DATE, '08.01.2017'),
        new Token(Type.EVENT_TIME, '13:05'),
        new Token(Type.GROUP_INFO, 'Es qualifizieren sich die 10 Zeitschnellsten (q) für A-/B-Finale, um 14:45'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '871'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hümke Lara'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LTV Bad Dürkheim'),
        new Token(Type.PERFORMANCE, '7,64'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.COMMENT, 'Verzicht auf Endlauf'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '894'),
        new Token(Type.ATHLETE_FULL_NAME, 'Grünnagel Lena-Marie'),
        new Token(Type.ATHLETE_YOB, '1991'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, '7,89'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.COMMENT, 'Verzicht auf Endlauf'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '900'),
        new Token(Type.ATHLETE_FULL_NAME, 'Krämer Nicole'),
        new Token(Type.ATHLETE_YOB, '1996'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, '7,93'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '953'),
        new Token(Type.ATHLETE_FULL_NAME, 'Stübinger Nathalie'),
        new Token(Type.ATHLETE_YOB, '1997'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Gimmeldingen'),
        new Token(Type.PERFORMANCE, '8,05'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '853'),
        new Token(Type.ATHLETE_FULL_NAME, 'Garay Nina'),
        new Token(Type.ATHLETE_YOB, '1995'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Region Karlsruhe'),
        new Token(Type.PERFORMANCE, '8,06'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.COMMENT, 'Verzicht auf Endlauf'),
        new Token(Type.DISCIPLINE_NAME, 'Stabhochsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Weibliche Jugend U18'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '08.01.2017'),
        new Token(Type.EVENT_TIME, '13:00'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '805'),
        new Token(Type.ATHLETE_FULL_NAME, 'Lorang Carola'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LC Rehlingen'),
        new Token(Type.PERFORMANCE, '2,70'),
        new Token(Type.HEIGHT, '2,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,40'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '2,50'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,60'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '2,70'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '2,80'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '745'),
        new Token(Type.ATHLETE_FULL_NAME, 'Fischer Paula'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ SAAR 05 Saarbrücken'),
        new Token(Type.PERFORMANCE, '2,40'),
        new Token(Type.HEIGHT, '2,30'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,40'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,50'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.DISCIPLINE_NAME, 'Hochsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U16'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '08.01.2017'),
        new Token(Type.EVENT_TIME, '13:00'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '895'),
        new Token(Type.ATHLETE_FULL_NAME, 'Plantz Liam'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, '1,63'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,48'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,51'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,54'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '1,57'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,60'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '1,63'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,66'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '841'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wagner Tim'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Bliestal'),
        new Token(Type.PERFORMANCE, '1,60'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,48'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,51'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,54'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,57'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,60'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,63'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '896'),
        new Token(Type.ATHLETE_FULL_NAME, 'Bogs Sven'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, '1,57'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,48'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,51'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,54'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,57'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,60'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '862'),
        new Token(Type.ATHLETE_FULL_NAME, 'Klauck Noah'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Reimsbach-Oppen'),
        new Token(Type.PERFORMANCE, '1,54'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,48'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,51'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,54'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,57'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '868'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wolf Guy'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LSG Sbr.-Sulzbachtal'),
        new Token(Type.PERFORMANCE, '1,51'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,48'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,51'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,54'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '820'),
        new Token(Type.ATHLETE_FULL_NAME, 'Marion Niklas'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LC Rehlingen'),
        new Token(Type.PERFORMANCE, '1,45'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,48'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '7'),
        new Token(Type.ATHLETE_BIB, '840'),
        new Token(Type.ATHLETE_FULL_NAME, 'Motsch Raphael'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Bliestal'),
        new Token(Type.PERFORMANCE, '1,45'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,40'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,48'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
