import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 24.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/24.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'Hallensportfest 2017 U14-U16'),
        new Token(Type.COMPETITION_CITY, 'Mainz'),
        new Token(Type.COMPETITION_VENUE, 'Hallensportfest'),
        new Token(Type.COMPETITION_START_DATE, '12.02.2017'),
        new Token(Type.DISCIPLINE_NAME, '60m'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W15'),
        new Token(Type.GROUP_NUMBER, '2'),
        new Token(Type.EVENT_DATE, '12.02.2017'),
        new Token(Type.EVENT_TIME, '09:52'),
        new Token(Type.GROUP_INFO, 'Es qualifizieren sich die 6 Zeitschnellsten (q) für Finale, um 11:30'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '79'),
        new Token(Type.ATHLETE_FULL_NAME, 'Berendsmeier Marie'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, '8,48'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, 'aW'),
        new Token(Type.ATHLETE_BIB, '21'),
        new Token(Type.ATHLETE_FULL_NAME, 'Spindler Lena'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, '8,27'),
        new Token(Type.ATHLETE_POSITION, 'aW'),
        new Token(Type.ATHLETE_BIB, '30'),
        new Token(Type.ATHLETE_FULL_NAME, 'Süss Nicola'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, '8,56'),
        new Token(Type.ATHLETE_BIB, '81'),
        new Token(Type.ATHLETE_FULL_NAME, 'Graffe Anja'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.DISCIPLINE_NAME, '60m'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W15'),
        new Token(Type.GROUP_NUMBER, '3'),
        new Token(Type.EVENT_DATE, '12.02.2017'),
        new Token(Type.EVENT_TIME, '09:54'),
        new Token(Type.GROUP_INFO, 'Es qualifizieren sich die 6 Zeitschnellsten (q) für Finale, um 11:30'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '92'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schmitt Lara'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, '8,47'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '88'),
        new Token(Type.ATHLETE_FULL_NAME, 'Vogt Jana'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, '8,58'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '86'),
        new Token(Type.ATHLETE_FULL_NAME, 'Mörschel Maret'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, '8,70'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '100'),
        new Token(Type.ATHLETE_FULL_NAME, 'Bodenheimer Emely'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SG Spiesheim'),
        new Token(Type.PERFORMANCE, '9,00'),
        new Token(Type.ATHLETE_POSITION, 'aW'),
        new Token(Type.ATHLETE_BIB, '102'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hees Hannah'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SG Spiesheim'),
        new Token(Type.PERFORMANCE, '8,86'),
        new Token(Type.DISCIPLINE_NAME, '60m'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W15'),
        new Token(Type.EVENT_DATE, '12.02.2017'),
        new Token(Type.EVENT_TIME, '11:30'),
        new Token(Type.ROUND_NAME, 'Finale'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '33'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schweikard Katharina'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TuS Saulheim'),
        new Token(Type.PERFORMANCE, '8,43'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '79'),
        new Token(Type.ATHLETE_FULL_NAME, 'Berendsmeier Marie'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, '8,49'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.COMMENT, '8,481'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '92'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schmitt Lara'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, '8,49'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./I'),
        new Token(Type.COMMENT, '8,487'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '88'),
        new Token(Type.ATHLETE_FULL_NAME, 'Vogt Jana'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, '8,62'),
        new Token(Type.GROUP_NUMBER_PLACE, '4./I'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '27'),
        new Token(Type.ATHLETE_FULL_NAME, 'Stark Anjuli'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, '8,66'),
        new Token(Type.GROUP_NUMBER_PLACE, '5./I'),
        new Token(Type.ATHLETE_BIB, '86'),
        new Token(Type.ATHLETE_FULL_NAME, 'Mörschel Maret'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.DISCIPLINE_NAME, '60m Hürden'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W15'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '762mm'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '12.02.2017'),
        new Token(Type.EVENT_TIME, '14:30'),
        new Token(Type.GROUP_INFO, 'Es qualifizieren sich die 4 Zeitschnellsten (q) für Finale, um 16:20'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '31'),
        new Token(Type.ATHLETE_FULL_NAME, 'Rong Alexandra'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV 1913 Nußdorf'),
        new Token(Type.PERFORMANCE, '9,83'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '90'),
        new Token(Type.ATHLETE_FULL_NAME, 'Weindorf Leonie'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, '10,06'),
        new Token(Type.ATHLETE_BIB, '92'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schmitt Lara'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, 'aufg.'),
        new Token(Type.DISCIPLINE_NAME, '60m Hürden'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W15'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '762mm'),
        new Token(Type.GROUP_NUMBER, '2'),
        new Token(Type.EVENT_DATE, '12.02.2017'),
        new Token(Type.EVENT_TIME, '14:35'),
        new Token(Type.GROUP_INFO, 'Es qualifizieren sich die 4 Zeitschnellsten (q) für Finale, um 16:20'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '27'),
        new Token(Type.ATHLETE_FULL_NAME, 'Stark Anjuli'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, '9,92'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '79'),
        new Token(Type.ATHLETE_FULL_NAME, 'Berendsmeier Marie'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, '10,20'),
        new Token(Type.ATHLETE_BIB, '33'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schweikard Katharina'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TuS Saulheim'),
        new Token(Type.PERFORMANCE, 'aufg.'),
        new Token(Type.ATHLETE_BIB, '35'),
        new Token(Type.ATHLETE_FULL_NAME, 'Gürsoy Rana'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TuS Saulheim'),
        new Token(Type.PERFORMANCE, 'n.a.'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
