import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 26.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/26.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'Pfalz Hallenmeisterschaften U20, U16'),
        new Token(Type.COMPETITION_CITY, 'Ludwigshafen'),
        new Token(Type.COMPETITION_VENUE, 'Leichtathletik Halle Ludwigshafen'),
        new Token(Type.COMPETITION_START_DATE, '14.01.2017'),
        new Token(Type.DISCIPLINE_NAME, 'Hochsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W14'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '14.01.2017'),
        new Token(Type.EVENT_TIME, '12:00'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '554'),
        new Token(Type.ATHLETE_FULL_NAME, 'Pietraß Cosima'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Nussdorf'),
        new Token(Type.PERFORMANCE, '1,45'),
        new Token(Type.HEIGHT, '1,25'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,38'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,41'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,47'),
        new Token(Type.HEIGHT_RESULT, 'r'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '426'),
        new Token(Type.ATHLETE_FULL_NAME, 'Leidner Hanna'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SG Bruchweiler'),
        new Token(Type.PERFORMANCE, '1,38'),
        new Token(Type.HEIGHT, '1,25'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,38'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,41'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '471'),
        new Token(Type.ATHLETE_FULL_NAME, 'Berlin Rebekka'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LC Hassloch'),
        new Token(Type.PERFORMANCE, '1,38'),
        new Token(Type.HEIGHT, '1,25'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '1,38'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '1,41'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '495'),
        new Token(Type.ATHLETE_FULL_NAME, 'Bischof Emily'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'ASV Landau'),
        new Token(Type.PERFORMANCE, '1,35'),
        new Token(Type.HEIGHT, '1,25'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,38'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '601'),
        new Token(Type.ATHLETE_FULL_NAME, 'Boegem Emilie'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Zweibrücken'),
        new Token(Type.PERFORMANCE, '1,30'),
        new Token(Type.HEIGHT, '1,25'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.DISCIPLINE_NAME, 'Stabhochsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W14'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '14.01.2017'),
        new Token(Type.EVENT_TIME, '12:00'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '618'),
        new Token(Type.ATHLETE_FULL_NAME, 'Rosar Leah'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Zweibrücken'),
        new Token(Type.PERFORMANCE, '2,70'),
        new Token(Type.HEIGHT, '2,00'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,10'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,20'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '2,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,40'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,50'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,60'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,70'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '2,80'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '615'),
        new Token(Type.ATHLETE_FULL_NAME, 'Mrowiec Emilie'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Zweibrücken'),
        new Token(Type.PERFORMANCE, '2,30'),
        new Token(Type.HEIGHT, '2,00'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,10'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '2,20'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,30'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,40'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '502'),
        new Token(Type.ATHLETE_FULL_NAME, 'Weigel Helene'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TG 04 Limburgerhof'),
        new Token(Type.PERFORMANCE, '2,10'),
        new Token(Type.HEIGHT, '2,00'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '2,10'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '2,20'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.DISCIPLINE_NAME, 'Weitsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W14'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '14.01.2017'),
        new Token(Type.EVENT_TIME, '14:00'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '540'),
        new Token(Type.ATHLETE_FULL_NAME, 'Brunn Carolin'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'VfL Neuhofen'),
        new Token(Type.PERFORMANCE, '4,78'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, '4,75'),
        new Token(Type.ATTEMPT3, 'x'),
        new Token(Type.ATTEMPT4, '4,33'),
        new Token(Type.ATTEMPT5, '-'),
        new Token(Type.ATTEMPT6, '4,78'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '463'),
        new Token(Type.ATHLETE_FULL_NAME, 'Gehrmann Anna'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG Grünstadt'),
        new Token(Type.PERFORMANCE, '4,74'),
        new Token(Type.ATTEMPT1, '4,30'),
        new Token(Type.ATTEMPT2, '4,48'),
        new Token(Type.ATTEMPT3, '4,48'),
        new Token(Type.ATTEMPT4, '4,62'),
        new Token(Type.ATTEMPT5, '4,74'),
        new Token(Type.ATTEMPT6, '4,48'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '554'),
        new Token(Type.ATHLETE_FULL_NAME, 'Pietraß Cosima'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Nussdorf'),
        new Token(Type.PERFORMANCE, '4,63'),
        new Token(Type.ATTEMPT1, '4,58'),
        new Token(Type.ATTEMPT2, '4,58'),
        new Token(Type.ATTEMPT3, '4,63'),
        new Token(Type.ATTEMPT4, '4,39'),
        new Token(Type.ATTEMPT5, '4,48'),
        new Token(Type.ATTEMPT6, '4,42'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '417'),
        new Token(Type.ATHLETE_FULL_NAME, 'Mayer Leonie'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LTV Bad Dürkheim'),
        new Token(Type.PERFORMANCE, '4,60'),
        new Token(Type.ATTEMPT1, '4,60'),
        new Token(Type.ATTEMPT2, '4,52'),
        new Token(Type.ATTEMPT3, '4,56'),
        new Token(Type.ATTEMPT4, '4,49'),
        new Token(Type.ATTEMPT5, '4,59'),
        new Token(Type.ATTEMPT6, '4,60'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '466'),
        new Token(Type.ATHLETE_FULL_NAME, 'Sandmann Hanna'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG Grünstadt'),
        new Token(Type.PERFORMANCE, '4,53'),
        new Token(Type.ATTEMPT1, '4,20'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, '4,53'),
        new Token(Type.ATTEMPT4, '4,36'),
        new Token(Type.ATTEMPT5, '-'),
        new Token(Type.ATTEMPT6, '4,44'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '604'),
        new Token(Type.ATHLETE_FULL_NAME, 'Fritzke Lisa'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Zweibrücken'),
        new Token(Type.PERFORMANCE, '4,42'),
        new Token(Type.ATTEMPT1, '4,34'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, '4,06'),
        new Token(Type.ATTEMPT4, '4,18'),
        new Token(Type.ATTEMPT5, '4,22'),
        new Token(Type.ATTEMPT6, '4,42'),
        new Token(Type.ATHLETE_POSITION, '7'),
        new Token(Type.ATHLETE_BIB, '451'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wolf Cora (YC)'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TPSV Enkenbach'),
        new Token(Type.PERFORMANCE, '4,39'),
        new Token(Type.ATTEMPT1, '4,39'),
        new Token(Type.ATTEMPT2, '4,10'),
        new Token(Type.ATTEMPT3, '4,12'),
        new Token(Type.ATTEMPT4, '4,03'),
        new Token(Type.ATTEMPT5, '-'),
        new Token(Type.ATTEMPT6, '3,93'),
        new Token(Type.ATHLETE_POSITION, '8'),
        new Token(Type.ATHLETE_BIB, '501'),
        new Token(Type.ATHLETE_FULL_NAME, 'Sasturain Viola'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TG 04 Limburgerhof'),
        new Token(Type.PERFORMANCE, '4,34'),
        new Token(Type.ATTEMPT1, '4,10'),
        new Token(Type.ATTEMPT2, '4,21'),
        new Token(Type.ATTEMPT3, '4,34'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, '4,17'),
        new Token(Type.ATTEMPT6, '4,23'),
        new Token(Type.ATHLETE_POSITION, '9'),
        new Token(Type.ATHLETE_BIB, '502'),
        new Token(Type.ATHLETE_FULL_NAME, 'Weigel Helene'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TG 04 Limburgerhof'),
        new Token(Type.PERFORMANCE, '4,09'),
        new Token(Type.ATTEMPT1, '3,99'),
        new Token(Type.ATTEMPT2, '3,96'),
        new Token(Type.ATTEMPT3, '4,09'),
        new Token(Type.ATHLETE_POSITION, '10'),
        new Token(Type.ATHLETE_BIB, '495'),
        new Token(Type.ATHLETE_FULL_NAME, 'Bischof Emily'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'ASV Landau'),
        new Token(Type.PERFORMANCE, '4,05'),
        new Token(Type.ATTEMPT1, '3,49'),
        new Token(Type.ATTEMPT2, '3,72'),
        new Token(Type.ATTEMPT3, '4,05'),
        new Token(Type.ATHLETE_POSITION, '11'),
        new Token(Type.ATHLETE_BIB, '516'),
        new Token(Type.ATHLETE_FULL_NAME, 'Mann Leonie'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'ABC Ludwigshafen'),
        new Token(Type.PERFORMANCE, '3,94'),
        new Token(Type.ATTEMPT1, '3,91'),
        new Token(Type.ATTEMPT2, '3,94'),
        new Token(Type.ATTEMPT3, '3,92'),
        new Token(Type.ATHLETE_POSITION, '12'),
        new Token(Type.ATHLETE_BIB, '465'),
        new Token(Type.ATHLETE_FULL_NAME, 'Philippsen Clara'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG Grünstadt'),
        new Token(Type.PERFORMANCE, '3,87'),
        new Token(Type.ATTEMPT1, '3,87'),
        new Token(Type.ATTEMPT2, '3,59'),
        new Token(Type.ATTEMPT3, 'x'),
        new Token(Type.ATHLETE_POSITION, '13'),
        new Token(Type.ATHLETE_BIB, '557'),
        new Token(Type.ATHLETE_FULL_NAME, 'Rottmann Sophie'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Nussdorf'),
        new Token(Type.PERFORMANCE, '3,85'),
        new Token(Type.ATTEMPT1, '3,85'),
        new Token(Type.ATTEMPT2, '3,58'),
        new Token(Type.ATTEMPT3, '3,61'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
