import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 27.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/27.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, '33. Nationales Vorweihnachtskriterium'),
        new Token(Type.COMPETITION_CITY, 'Stadtallendorf'),
        new Token(Type.COMPETITION_VENUE, 'Herrenwaldhalle'),
        new Token(Type.COMPETITION_START_DATE, '10.12.2016'),
        new Token(Type.DISCIPLINE_NAME, 'Hochsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Kinder W11'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '11.12.2016'),
        new Token(Type.EVENT_TIME, '14:20'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '239'),
        new Token(Type.ATHLETE_FULL_NAME, 'Reh Fanny'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Eschweger TSV'),
        new Token(Type.PERFORMANCE, '1,35'),
        new Token(Type.HEIGHT, '0,95'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,00'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,05'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,10'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,15'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,20'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,23'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,26'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,29'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,32'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,38'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '617'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kemp Jill'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Bigge-Olsberg'),
        new Token(Type.PERFORMANCE, '1,32'),
        new Token(Type.HEIGHT, '0,95'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,00'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,05'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,10'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,15'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,20'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,23'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,26'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,29'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,32'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '526'),
        new Token(Type.ATHLETE_FULL_NAME, 'Utermarck Merle'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, '1,32'),
        new Token(Type.HEIGHT, '0,95'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,00'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,05'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,10'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,15'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,20'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,23'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,26'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,29'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,32'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '1,35'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '315'),
        new Token(Type.ATHLETE_FULL_NAME, 'Möller Alessia'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAV Kassel'),
        new Token(Type.PERFORMANCE, '1,29'),
        new Token(Type.HEIGHT, '0,95'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,00'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,05'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,10'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,15'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,20'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,23'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,26'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,29'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,32'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '618'),
        new Token(Type.ATHLETE_FULL_NAME, 'Klauke Mara'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Bigge-Olsberg'),
        new Token(Type.PERFORMANCE, '1,29'),
        new Token(Type.HEIGHT, '0,95'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,00'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,05'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,10'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,15'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,20'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,23'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,26'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '1,29'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,32'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '442'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hochdörffer Lara'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Wittgenstein'),
        new Token(Type.PERFORMANCE, '1,29'),
        new Token(Type.HEIGHT, '0,95'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,00'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,05'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,10'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,15'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,20'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,23'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,26'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,29'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,32'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '7'),
        new Token(Type.ATHLETE_BIB, '217'),
        new Token(Type.ATHLETE_FULL_NAME, 'Freund Marlisa'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'ASC 1990 Breidenbach'),
        new Token(Type.PERFORMANCE, '1,26'),
        new Token(Type.HEIGHT, '0,95'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,00'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,05'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,10'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,15'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,20'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,23'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,26'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,29'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '8'),
        new Token(Type.ATHLETE_BIB, '588'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schade Madeleine'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV 05 Remsfeld'),
        new Token(Type.PERFORMANCE, '1,26'),
        new Token(Type.HEIGHT, '0,95'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,00'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,05'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,10'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,15'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,20'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,23'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,26'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,29'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '9'),
        new Token(Type.ATHLETE_BIB, '313'),
        new Token(Type.ATHLETE_FULL_NAME, 'Chmilewski Lotte'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAV Kassel'),
        new Token(Type.PERFORMANCE, '1,23'),
        new Token(Type.HEIGHT, '0,95'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,00'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,05'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,10'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,15'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,20'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,23'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,26'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '10'),
        new Token(Type.ATHLETE_BIB, '314'),
        new Token(Type.ATHLETE_FULL_NAME, 'Dejmny Sophia'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAV Kassel'),
        new Token(Type.PERFORMANCE, '1,20'),
        new Token(Type.HEIGHT, '0,95'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,00'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,05'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,10'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,15'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,20'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,23'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '11'),
        new Token(Type.ATHLETE_BIB, '216'),
        new Token(Type.ATHLETE_FULL_NAME, 'Freund Nela'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'ASC 1990 Breidenbach'),
        new Token(Type.PERFORMANCE, '1,20'),
        new Token(Type.HEIGHT, '0,95'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,00'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,05'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,10'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,15'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,20'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,23'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '11'),
        new Token(Type.ATHLETE_BIB, '682'),
        new Token(Type.ATHLETE_FULL_NAME, 'Sackewitz Milena'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Kirchhain'),
        new Token(Type.PERFORMANCE, '1,20'),
        new Token(Type.HEIGHT, '0,95'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,00'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,05'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,10'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,15'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,20'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,23'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '13'),
        new Token(Type.ATHLETE_BIB, '203'),
        new Token(Type.ATHLETE_FULL_NAME, 'Sorg Charlotte'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Alsfelder SC 96'),
        new Token(Type.PERFORMANCE, '1,20'),
        new Token(Type.HEIGHT, '0,95'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,00'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,05'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,10'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,15'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,20'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '1,23'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '14'),
        new Token(Type.ATHLETE_BIB, '441'),
        new Token(Type.ATHLETE_FULL_NAME, 'Walle Franziska'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Wittgenstein'),
        new Token(Type.PERFORMANCE, '1,10'),
        new Token(Type.HEIGHT, '0,95'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,00'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,05'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,10'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,15'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '15'),
        new Token(Type.ATHLETE_BIB, '316'),
        new Token(Type.ATHLETE_FULL_NAME, 'Lopata Anastasia'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAV Kassel'),
        new Token(Type.PERFORMANCE, '1,00'),
        new Token(Type.HEIGHT, '0,95'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,00'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,05'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_BIB, '445'),
        new Token(Type.ATHLETE_FULL_NAME, 'Keller Aayliah'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Wittgenstein'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.ATHLETE_BIB, '437'),
        new Token(Type.ATHLETE_FULL_NAME, 'Saul Lucy'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Wettenberg'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.ATHLETE_BIB, '434'),
        new Token(Type.ATHLETE_FULL_NAME, 'Rüspeler Lynn'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Wettenberg'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.ATHLETE_BIB, '771'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schäfer Josceline'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Lauterbach'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.ATHLETE_BIB, '525'),
        new Token(Type.ATHLETE_FULL_NAME, 'Heusinger v.Waldegge Carlotta'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.ATHLETE_BIB, '269'),
        new Token(Type.ATHLETE_FULL_NAME, 'Okuku Holly'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'GSV Eintracht Baunatal'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.COMMENT, 'b'),
        new Token(Type.DISCIPLINE_NAME, 'Weitsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Kinder W11'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '11.12.2016'),
        new Token(Type.EVENT_TIME, '12:30'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '269'),
        new Token(Type.ATHLETE_FULL_NAME, 'Okuku Holly'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'GSV Eintracht Baunatal'),
        new Token(Type.PERFORMANCE, '4,50'),
        new Token(Type.ATTEMPT1, '4,18'),
        new Token(Type.ATTEMPT2, '4,46'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATTEMPT4, '4,02'),
        new Token(Type.ATTEMPT5, '4,00'),
        new Token(Type.ATTEMPT6, '4,50'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '526'),
        new Token(Type.ATHLETE_FULL_NAME, 'Utermarck Merle'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, '4,39'),
        new Token(Type.ATTEMPT1, '4,03'),
        new Token(Type.ATTEMPT2, '4,06'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATTEMPT4, '4,28'),
        new Token(Type.ATTEMPT5, '4,17'),
        new Token(Type.ATTEMPT6, '4,39'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '315'),
        new Token(Type.ATHLETE_FULL_NAME, 'Möller Alessia'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAV Kassel'),
        new Token(Type.PERFORMANCE, '4,37'),
        new Token(Type.ATTEMPT1, '4,10'),
        new Token(Type.ATTEMPT2, '4,14'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATTEMPT4, '4,20'),
        new Token(Type.ATTEMPT5, '4,30'),
        new Token(Type.ATTEMPT6, '4,37'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '442'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hochdörffer Lara'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Wittgenstein'),
        new Token(Type.PERFORMANCE, '4,27'),
        new Token(Type.ATTEMPT1, '3,94'),
        new Token(Type.ATTEMPT2, '4,10'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATTEMPT4, '4,19'),
        new Token(Type.ATTEMPT5, '4,27'),
        new Token(Type.ATTEMPT6, '4,18'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '239'),
        new Token(Type.ATHLETE_FULL_NAME, 'Reh Fanny'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Eschweger TSV'),
        new Token(Type.PERFORMANCE, '4,27'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, '4,12'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATTEMPT4, '4,18'),
        new Token(Type.ATTEMPT5, '4,27'),
        new Token(Type.ATTEMPT6, 'x'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '434'),
        new Token(Type.ATHLETE_FULL_NAME, 'Rüspeler Lynn'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Wettenberg'),
        new Token(Type.PERFORMANCE, '4,21'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, '4,09'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATTEMPT4, '4,01'),
        new Token(Type.ATTEMPT5, '4,02'),
        new Token(Type.ATTEMPT6, '4,21'),
        new Token(Type.ATHLETE_POSITION, '7'),
        new Token(Type.ATHLETE_BIB, '377'),
        new Token(Type.ATHLETE_FULL_NAME, 'Oeste Carolina'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Alheimer/Rotenburg-Bebra'),
        new Token(Type.PERFORMANCE, '4,08'),
        new Token(Type.ATTEMPT1, '3,93'),
        new Token(Type.ATTEMPT2, '4,03'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, '3,96'),
        new Token(Type.ATTEMPT6, '4,08'),
        new Token(Type.ATHLETE_POSITION, '8'),
        new Token(Type.ATHLETE_BIB, '313'),
        new Token(Type.ATHLETE_FULL_NAME, 'Chmilewski Lotte'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAV Kassel'),
        new Token(Type.PERFORMANCE, '4,04'),
        new Token(Type.ATTEMPT1, '4,01'),
        new Token(Type.ATTEMPT2, '3,95'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATTEMPT4, '4,04'),
        new Token(Type.ATTEMPT5, '3,97'),
        new Token(Type.ATTEMPT6, '3,97'),
        new Token(Type.ATHLETE_POSITION, '9'),
        new Token(Type.ATHLETE_BIB, '374'),
        new Token(Type.ATHLETE_FULL_NAME, 'Grunwald Joahnna'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Alheimer/Rotenburg-Bebra'),
        new Token(Type.PERFORMANCE, '3,92'),
        new Token(Type.ATTEMPT1, '3,92'),
        new Token(Type.ATTEMPT2, '3,77'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATHLETE_POSITION, '10'),
        new Token(Type.ATHLETE_BIB, '682'),
        new Token(Type.ATHLETE_FULL_NAME, 'Sackewitz Milena'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Kirchhain'),
        new Token(Type.PERFORMANCE, '3,89'),
        new Token(Type.ATTEMPT1, '3,84'),
        new Token(Type.ATTEMPT2, '3,89'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.ATHLETE_POSITION, '11'),
        new Token(Type.ATHLETE_BIB, '437'),
        new Token(Type.ATHLETE_FULL_NAME, 'Saul Lucy'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Wettenberg'),
        new Token(Type.PERFORMANCE, '3,88'),
        new Token(Type.ATTEMPT1, '3,88'),
        new Token(Type.ATTEMPT2, '3,77'),
        new Token(Type.ATTEMPT3, '-'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
