import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 28.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/28.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'Kreismeisterschaften Drei-/Vierkampf'),
        new Token(Type.COMPETITION_CITY, ''),
        new Token(Type.COMPETITION_VENUE, 'Bergisch Gladbach'),
        new Token(Type.COMPETITION_START_DATE, '24.09.2016'),
        new Token(Type.DISCIPLINE_NAME, 'Vierkampf'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend M15'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, 'aus gemeinsamen Bewerb'),
        new Token(Type.EVENT_DATE, '24.09.2016'),
        new Token(Type.PARTICIPANT_COUNT, '7'),
        new Token(Type.ROUND_NAME, 'Finalstand'),
        new Token(Type.COMBINED_DISCIPLINE, '100'),
        new Token(Type.COMBINED_DISCIPLINE, 'WEI'),
        new Token(Type.COMBINED_DISCIPLINE, 'HOC'),
        new Token(Type.COMBINED_DISCIPLINE, 'KUG'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '839'),
        new Token(Type.ATHLETE_FULL_NAME, 'Stein Jannik'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_CLUB_NAME, 'VfL Engelskirchen'),
        new Token(Type.PERFORMANCE, '1.894'),
        new Token(Type.COMBINED_PERFORMANCE, '13,80', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '5,10', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,54', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '9,82', 'KUG'),
        new Token(Type.COMBINED_WIND, '0,0', '100'),
        new Token(Type.COMBINED_POINTS, '429', '100'),
        new Token(Type.COMBINED_POINTS, '505', 'WEI'),
        new Token(Type.COMBINED_POINTS, '499', 'HOC'),
        new Token(Type.COMBINED_POINTS, '461', 'KUG'),
        new Token(Type.COMBINED_SUM, '429', '100'),
        new Token(Type.COMBINED_SUM, '934', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.433', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.894', 'KUG'),
        new Token(Type.DISCIPLINE_NAME, 'Vierkampf'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend M14'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, 'aus gemeinsamen Bewerb'),
        new Token(Type.EVENT_DATE, '24.09.2016'),
        new Token(Type.PARTICIPANT_COUNT, '7'),
        new Token(Type.ROUND_NAME, 'Finalstand'),
        new Token(Type.COMBINED_DISCIPLINE, '100'),
        new Token(Type.COMBINED_DISCIPLINE, 'WEI'),
        new Token(Type.COMBINED_DISCIPLINE, 'HOC'),
        new Token(Type.COMBINED_DISCIPLINE, 'KUG'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '696'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kötter Nico'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'DJK Montania Kürten'),
        new Token(Type.PERFORMANCE, '1.817'),
        new Token(Type.COMBINED_PERFORMANCE, '13,69', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '4,33', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,50', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '10,17', 'KUG'),
        new Token(Type.COMBINED_WIND, '0,0', '100'),
        new Token(Type.COMBINED_POINTS, '438', '100'),
        new Token(Type.COMBINED_POINTS, '424', 'WEI'),
        new Token(Type.COMBINED_POINTS, '479', 'HOC'),
        new Token(Type.COMBINED_POINTS, '476', 'KUG'),
        new Token(Type.COMBINED_SUM, '438', '100'),
        new Token(Type.COMBINED_SUM, '862', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.341', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.817', 'KUG'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '697'),
        new Token(Type.ATHLETE_FULL_NAME, 'Theisen Adrian'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'DJK Montania Kürten'),
        new Token(Type.PERFORMANCE, '1.775'),
        new Token(Type.COMBINED_PERFORMANCE, '13,64', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '4,71', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,34', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '10,09', 'KUG'),
        new Token(Type.COMBINED_WIND, '0,0', '100'),
        new Token(Type.COMBINED_POINTS, '442', '100'),
        new Token(Type.COMBINED_POINTS, '465', 'WEI'),
        new Token(Type.COMBINED_POINTS, '395', 'HOC'),
        new Token(Type.COMBINED_POINTS, '473', 'KUG'),
        new Token(Type.COMBINED_SUM, '442', '100'),
        new Token(Type.COMBINED_SUM, '907', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.302', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.775', 'KUG'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '809'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schommer Kilian'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Herkenrath'),
        new Token(Type.PERFORMANCE, '1.459'),
        new Token(Type.COMBINED_PERFORMANCE, '14,82', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '4,45', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,34', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '5,88', 'KUG'),
        new Token(Type.COMBINED_WIND, '0,0', '100'),
        new Token(Type.COMBINED_POINTS, '356', '100'),
        new Token(Type.COMBINED_POINTS, '438', 'WEI'),
        new Token(Type.COMBINED_POINTS, '395', 'HOC'),
        new Token(Type.COMBINED_POINTS, '270', 'KUG'),
        new Token(Type.COMBINED_SUM, '356', '100'),
        new Token(Type.COMBINED_SUM, '794', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.189', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.459', 'KUG'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '762'),
        new Token(Type.ATHLETE_FULL_NAME, 'Ems Sebastian'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SC Oberodenthal'),
        new Token(Type.PERFORMANCE, '1.446'),
        new Token(Type.COMBINED_PERFORMANCE, '15,61', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '4,07', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,30', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '7,87', 'KUG'),
        new Token(Type.COMBINED_WIND, '0,0', '100'),
        new Token(Type.COMBINED_POINTS, '305', '100'),
        new Token(Type.COMBINED_POINTS, '395', 'WEI'),
        new Token(Type.COMBINED_POINTS, '373', 'HOC'),
        new Token(Type.COMBINED_POINTS, '373', 'KUG'),
        new Token(Type.COMBINED_SUM, '305', '100'),
        new Token(Type.COMBINED_SUM, '700', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.073', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.446', 'KUG'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '698'),
        new Token(Type.ATHLETE_FULL_NAME, 'Koch Florian'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'DJK Montania Kürten'),
        new Token(Type.PERFORMANCE, '1.313'),
        new Token(Type.COMBINED_PERFORMANCE, '15,21', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '3,95', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,26', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '5,53', 'KUG'),
        new Token(Type.COMBINED_WIND, '0,0', '100'),
        new Token(Type.COMBINED_POINTS, '330', '100'),
        new Token(Type.COMBINED_POINTS, '382', 'WEI'),
        new Token(Type.COMBINED_POINTS, '351', 'HOC'),
        new Token(Type.COMBINED_POINTS, '250', 'KUG'),
        new Token(Type.COMBINED_SUM, '330', '100'),
        new Token(Type.COMBINED_SUM, '712', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.063', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.313', 'KUG'),
        new Token(Type.ATHLETE_BIB, '819'),
        new Token(Type.ATHLETE_FULL_NAME, 'Böhmer Luca'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Herkenrath'),
        new Token(Type.PERFORMANCE, 'DNF'),
        new Token(Type.COMBINED_PERFORMANCE, 'Dns', '100'),
        new Token(Type.COMBINED_PERFORMANCE, 'Dns', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, 'Dns', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, 'Dns', 'KUG'),
        new Token(Type.COMBINED_WIND, '0,0', '100'),
        new Token(Type.COMBINED_POINTS, '0', '100'),
        new Token(Type.COMBINED_POINTS, '0', 'WEI'),
        new Token(Type.COMBINED_POINTS, '0', 'HOC'),
        new Token(Type.COMBINED_POINTS, '0', 'KUG'),
        new Token(Type.COMBINED_SUM, '0', '100'),
        new Token(Type.COMBINED_SUM, '0', 'WEI'),
        new Token(Type.COMBINED_SUM, '0', 'HOC'),
        new Token(Type.COMBINED_SUM, '0', 'KUG'),
        new Token(Type.DISCIPLINE_NAME, 'Vierkampf Mannschaft MJU16'),
        new Token(Type.AGE_GROUP_NAME, 'M15, M14'),
        new Token(Type.DISCIPLINE_NAME, 'Vierkampf'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W14'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, 'aus gemeinsamen Bewerb'),
        new Token(Type.EVENT_DATE, '24.09.2016'),
        new Token(Type.PARTICIPANT_COUNT, '11'),
        new Token(Type.ROUND_NAME, 'Finalstand'),
        new Token(Type.COMBINED_DISCIPLINE, '100'),
        new Token(Type.COMBINED_DISCIPLINE, 'WEI'),
        new Token(Type.COMBINED_DISCIPLINE, 'HOC'),
        new Token(Type.COMBINED_DISCIPLINE, 'KUG'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '828'),
        new Token(Type.ATHLETE_FULL_NAME, 'Komp Lina'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'VfL Engelskirchen'),
        new Token(Type.PERFORMANCE, '1.818'),
        new Token(Type.COMBINED_PERFORMANCE, '14,24', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '4,75', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,42', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '7,80', 'KUG'),
        new Token(Type.COMBINED_WIND, '-0,9', '100'),
        new Token(Type.COMBINED_POINTS, '459', '100'),
        new Token(Type.COMBINED_POINTS, '522', 'WEI'),
        new Token(Type.COMBINED_POINTS, '457', 'HOC'),
        new Token(Type.COMBINED_POINTS, '380', 'KUG'),
        new Token(Type.COMBINED_SUM, '459', '100'),
        new Token(Type.COMBINED_SUM, '981', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.438', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.818', 'KUG'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '752'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kraus Jennifer'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Wipperfüth'),
        new Token(Type.PERFORMANCE, '1.756'),
        new Token(Type.COMBINED_PERFORMANCE, '15,28', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '4,08', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,42', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '9,88', 'KUG'),
        new Token(Type.COMBINED_WIND, '-0,7', '100'),
        new Token(Type.COMBINED_POINTS, '386', '100'),
        new Token(Type.COMBINED_POINTS, '445', 'WEI'),
        new Token(Type.COMBINED_POINTS, '457', 'HOC'),
        new Token(Type.COMBINED_POINTS, '468', 'KUG'),
        new Token(Type.COMBINED_SUM, '386', '100'),
        new Token(Type.COMBINED_SUM, '831', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.288', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.756', 'KUG'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '734'),
        new Token(Type.ATHLETE_FULL_NAME, 'Luyven Marietta'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Leichlinger TV'),
        new Token(Type.PERFORMANCE, '1.643'),
        new Token(Type.COMBINED_PERFORMANCE, '14,41', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '4,04', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,34', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '7,13', 'KUG'),
        new Token(Type.COMBINED_WIND, '-0,9', '100'),
        new Token(Type.COMBINED_POINTS, '447', '100'),
        new Token(Type.COMBINED_POINTS, '440', 'WEI'),
        new Token(Type.COMBINED_POINTS, '407', 'HOC'),
        new Token(Type.COMBINED_POINTS, '349', 'KUG'),
        new Token(Type.COMBINED_SUM, '447', '100'),
        new Token(Type.COMBINED_SUM, '887', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.294', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.643', 'KUG'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '837'),
        new Token(Type.ATHLETE_FULL_NAME, 'Lorenz Louisa-Marie'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'VfL Engelskirchen'),
        new Token(Type.PERFORMANCE, '1.618'),
        new Token(Type.COMBINED_PERFORMANCE, '14,44', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '4,46', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,26', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '6,74', 'KUG'),
        new Token(Type.COMBINED_WIND, '-0,9', '100'),
        new Token(Type.COMBINED_POINTS, '444', '100'),
        new Token(Type.COMBINED_POINTS, '489', 'WEI'),
        new Token(Type.COMBINED_POINTS, '355', 'HOC'),
        new Token(Type.COMBINED_POINTS, '330', 'KUG'),
        new Token(Type.COMBINED_SUM, '444', '100'),
        new Token(Type.COMBINED_SUM, '933', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.288', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.618', 'KUG'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '699'),
        new Token(Type.ATHLETE_FULL_NAME, 'Laudenberg Yasmin'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'DJK Montania Kürten'),
        new Token(Type.PERFORMANCE, '1.561'),
        new Token(Type.COMBINED_PERFORMANCE, '15,14', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '4,18', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,34', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '6,15', 'KUG'),
        new Token(Type.COMBINED_WIND, '-0,9', '100'),
        new Token(Type.COMBINED_POINTS, '396', '100'),
        new Token(Type.COMBINED_POINTS, '457', 'WEI'),
        new Token(Type.COMBINED_POINTS, '407', 'HOC'),
        new Token(Type.COMBINED_POINTS, '301', 'KUG'),
        new Token(Type.COMBINED_SUM, '396', '100'),
        new Token(Type.COMBINED_SUM, '853', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.260', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.561', 'KUG'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '806'),
        new Token(Type.ATHLETE_FULL_NAME, 'Haas Kiana'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Herkenrath'),
        new Token(Type.PERFORMANCE, '1.448'),
        new Token(Type.COMBINED_PERFORMANCE, '14,57', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '3,52', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,22', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '6,29', 'KUG'),
        new Token(Type.COMBINED_WIND, '-0,7', '100'),
        new Token(Type.COMBINED_POINTS, '435', '100'),
        new Token(Type.COMBINED_POINTS, '376', 'WEI'),
        new Token(Type.COMBINED_POINTS, '329', 'HOC'),
        new Token(Type.COMBINED_POINTS, '308', 'KUG'),
        new Token(Type.COMBINED_SUM, '435', '100'),
        new Token(Type.COMBINED_SUM, '811', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.140', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.448', 'KUG'),
        new Token(Type.ATHLETE_POSITION, '7'),
        new Token(Type.ATHLETE_BIB, '805'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wienand Clara'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Herkenrath'),
        new Token(Type.PERFORMANCE, '1.423'),
        new Token(Type.COMBINED_PERFORMANCE, '14,46', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '3,64', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,10', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '6,99', 'KUG'),
        new Token(Type.COMBINED_WIND, '-0,7', '100'),
        new Token(Type.COMBINED_POINTS, '443', '100'),
        new Token(Type.COMBINED_POINTS, '391', 'WEI'),
        new Token(Type.COMBINED_POINTS, '247', 'HOC'),
        new Token(Type.COMBINED_POINTS, '342', 'KUG'),
        new Token(Type.COMBINED_SUM, '443', '100'),
        new Token(Type.COMBINED_SUM, '834', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.081', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.423', 'KUG'),
        new Token(Type.ATHLETE_POSITION, '8'),
        new Token(Type.ATHLETE_BIB, '740'),
        new Token(Type.ATHLETE_FULL_NAME, 'Klopp Anna-Lena'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Leichlinger TV'),
        new Token(Type.PERFORMANCE, '1.054'),
        new Token(Type.COMBINED_PERFORMANCE, '16,17', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '3,64', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, 'ogV', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '6,76', 'KUG'),
        new Token(Type.COMBINED_WIND, '-0,9', '100'),
        new Token(Type.COMBINED_POINTS, '332', '100'),
        new Token(Type.COMBINED_POINTS, '391', 'WEI'),
        new Token(Type.COMBINED_POINTS, '0', 'HOC'),
        new Token(Type.COMBINED_POINTS, '331', 'KUG'),
        new Token(Type.COMBINED_SUM, '332', '100'),
        new Token(Type.COMBINED_SUM, '723', 'WEI'),
        new Token(Type.COMBINED_SUM, '723', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.054', 'KUG'),
        new Token(Type.ATHLETE_BIB, '813'),
        new Token(Type.ATHLETE_FULL_NAME, 'Meiger Marie'),
        new Token(Type.ATHLETE_YOB, '2002'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Herkenrath'),
        new Token(Type.PERFORMANCE, 'DNF'),
        new Token(Type.COMBINED_PERFORMANCE, 'Dns', '100'),
        new Token(Type.COMBINED_PERFORMANCE, 'Dns', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, 'ogV', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, 'Dns', 'KUG'),
        new Token(Type.COMBINED_WIND, '-0,7', '100'),
        new Token(Type.COMBINED_POINTS, '0', '100'),
        new Token(Type.COMBINED_POINTS, '0', 'WEI'),
        new Token(Type.COMBINED_POINTS, '0', 'HOC'),
        new Token(Type.COMBINED_POINTS, '0', 'KUG'),
        new Token(Type.COMBINED_SUM, '0', '100'),
        new Token(Type.COMBINED_SUM, '0', 'WEI'),
        new Token(Type.COMBINED_SUM, '0', 'HOC'),
        new Token(Type.COMBINED_SUM, '0', 'KUG'),
        new Token(Type.DISCIPLINE_NAME, 'Vierkampf'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend W15'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, 'aus gemeinsamen Bewerb'),
        new Token(Type.EVENT_DATE, '24.09.2016'),
        new Token(Type.PARTICIPANT_COUNT, '11'),
        new Token(Type.ROUND_NAME, 'Finalstand'),
        new Token(Type.COMBINED_DISCIPLINE, '100'),
        new Token(Type.COMBINED_DISCIPLINE, 'WEI'),
        new Token(Type.COMBINED_DISCIPLINE, 'HOC'),
        new Token(Type.COMBINED_DISCIPLINE, 'KUG'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '843'),
        new Token(Type.ATHLETE_FULL_NAME, 'Sübben Emily'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Wiehltaler LC'),
        new Token(Type.PERFORMANCE, '1.605'),
        new Token(Type.COMBINED_PERFORMANCE, '14,95', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '4,24', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,38', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '6,14', 'KUG'),
        new Token(Type.COMBINED_WIND, '-0,9', '100'),
        new Token(Type.COMBINED_POINTS, '408', '100'),
        new Token(Type.COMBINED_POINTS, '464', 'WEI'),
        new Token(Type.COMBINED_POINTS, '432', 'HOC'),
        new Token(Type.COMBINED_POINTS, '301', 'KUG'),
        new Token(Type.COMBINED_SUM, '408', '100'),
        new Token(Type.COMBINED_SUM, '872', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.304', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.605', 'KUG'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '807'),
        new Token(Type.ATHLETE_FULL_NAME, 'Ichite Roseline'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Herkenrath'),
        new Token(Type.PERFORMANCE, '1.592'),
        new Token(Type.COMBINED_PERFORMANCE, '15,20', '100'),
        new Token(Type.COMBINED_PERFORMANCE, '4,16', 'WEI'),
        new Token(Type.COMBINED_PERFORMANCE, '1,38', 'HOC'),
        new Token(Type.COMBINED_PERFORMANCE, '6,40', 'KUG'),
        new Token(Type.COMBINED_WIND, '-0,7', '100'),
        new Token(Type.COMBINED_POINTS, '392', '100'),
        new Token(Type.COMBINED_POINTS, '454', 'WEI'),
        new Token(Type.COMBINED_POINTS, '432', 'HOC'),
        new Token(Type.COMBINED_POINTS, '314', 'KUG'),
        new Token(Type.COMBINED_SUM, '392', '100'),
        new Token(Type.COMBINED_SUM, '846', 'WEI'),
        new Token(Type.COMBINED_SUM, '1.278', 'HOC'),
        new Token(Type.COMBINED_SUM, '1.592', 'KUG'),
        new Token(Type.DISCIPLINE_NAME, 'Vierkampf Mannschaft WJU16'),
        new Token(Type.AGE_GROUP_NAME, 'W15, W14'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
