import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 29.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/29.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, '37.  Schülersportfest U12 MK'),
        new Token(Type.COMPETITION_CITY, 'Langen'),
        new Token(Type.COMPETITION_VENUE, 'SSG Freizeitcenter'),
        new Token(Type.COMPETITION_START_DATE, '18.09.2016'),
        new Token(Type.DISCIPLINE_NAME, '50m (3-K)'),
        new Token(Type.AGE_GROUP_NAME, 'Kinder M11'),
        new Token(Type.EVENT_DATE, '18.09.2016'),
        new Token(Type.EVENT_TIME, '12:00'),
        new Token(Type.ROUND_NAME, 'Dreikampf'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '13'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hoch Nicolas'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Langen'),
        new Token(Type.PERFORMANCE, '7,94'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.POINTS, '363'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '25'),
        new Token(Type.ATHLETE_FULL_NAME, 'Almasan Fabian'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SG Egelsbach'),
        new Token(Type.PERFORMANCE, '8,28'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.POINTS, '325'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '42'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wagner Aaron'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TS Ober-Roden'),
        new Token(Type.PERFORMANCE, '8,86'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./I'),
        new Token(Type.POINTS, '268'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '10'),
        new Token(Type.ATHLETE_FULL_NAME, 'Bürkle Jacob'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Langen'),
        new Token(Type.PERFORMANCE, '9,05'),
        new Token(Type.GROUP_NUMBER_PLACE, '4./I'),
        new Token(Type.POINTS, '251'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '14'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schiller Leonard'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Langen'),
        new Token(Type.PERFORMANCE, '9,31'),
        new Token(Type.GROUP_NUMBER_PLACE, '5./I'),
        new Token(Type.POINTS, '229'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '19'),
        new Token(Type.ATHLETE_FULL_NAME, 'Sturm Viktor'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SKG Sprendlingen'),
        new Token(Type.PERFORMANCE, '9,50'),
        new Token(Type.GROUP_NUMBER_PLACE, '6./I'),
        new Token(Type.POINTS, '213'),
        new Token(Type.DISCIPLINE_NAME, 'Weitsprung (3-K)'),
        new Token(Type.AGE_GROUP_NAME, 'Kinder M11'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '18.09.2016'),
        new Token(Type.EVENT_TIME, '10:45'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '13'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hoch Nicolas'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Langen'),
        new Token(Type.PERFORMANCE, '3,78'),
        new Token(Type.POINTS, '362'),
        new Token(Type.ATTEMPT1, '3,20'),
        new Token(Type.ATTEMPT2, '3,30'),
        new Token(Type.ATTEMPT3, '3,78'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '25'),
        new Token(Type.ATHLETE_FULL_NAME, 'Almasan Fabian'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SG Egelsbach'),
        new Token(Type.PERFORMANCE, '3,73'),
        new Token(Type.POINTS, '356'),
        new Token(Type.ATTEMPT1, '3,73'),
        new Token(Type.ATTEMPT2, '3,57'),
        new Token(Type.ATTEMPT3, '3,61'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '42'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wagner Aaron'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TS Ober-Roden'),
        new Token(Type.PERFORMANCE, '3,40'),
        new Token(Type.POINTS, '316'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, '3,40'),
        new Token(Type.ATTEMPT3, '3,22'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '19'),
        new Token(Type.ATHLETE_FULL_NAME, 'Sturm Viktor'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SKG Sprendlingen'),
        new Token(Type.PERFORMANCE, '3,24'),
        new Token(Type.POINTS, '296'),
        new Token(Type.ATTEMPT1, '3,24'),
        new Token(Type.ATTEMPT2, '2,96'),
        new Token(Type.ATTEMPT3, '2,97'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '10'),
        new Token(Type.ATHLETE_FULL_NAME, 'Bürkle Jacob'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Langen'),
        new Token(Type.PERFORMANCE, '3,04'),
        new Token(Type.POINTS, '270'),
        new Token(Type.ATTEMPT1, '2,93'),
        new Token(Type.ATTEMPT2, '3,04'),
        new Token(Type.ATTEMPT3, '2,92'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '14'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schiller Leonard'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Langen'),
        new Token(Type.PERFORMANCE, '2,93'),
        new Token(Type.POINTS, '256'),
        new Token(Type.ATTEMPT1, '2,93'),
        new Token(Type.ATTEMPT2, '2,84'),
        new Token(Type.ATTEMPT3, '2,90'),
        new Token(Type.ATHLETE_BIB, '35'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wolf Christian'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Bruchköbel'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.DISCIPLINE_NAME, 'Schlagballwurf (3-K)'),
        new Token(Type.AGE_GROUP_NAME, 'Kinder M11'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '80g'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '18.09.2016'),
        new Token(Type.EVENT_TIME, '11:00'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '42'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wagner Aaron'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TS Ober-Roden'),
        new Token(Type.PERFORMANCE, '30,50'),
        new Token(Type.POINTS, '247'),
        new Token(Type.ATTEMPT1, '26,00'),
        new Token(Type.ATTEMPT2, '30,50'),
        new Token(Type.ATTEMPT3, '29,00'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '13'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hoch Nicolas'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Langen'),
        new Token(Type.PERFORMANCE, '25,00'),
        new Token(Type.POINTS, '200'),
        new Token(Type.ATTEMPT1, '24,00'),
        new Token(Type.ATTEMPT2, '24,00'),
        new Token(Type.ATTEMPT3, '25,00'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '19'),
        new Token(Type.ATHLETE_FULL_NAME, 'Sturm Viktor'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SKG Sprendlingen'),
        new Token(Type.PERFORMANCE, '24,00'),
        new Token(Type.POINTS, '190'),
        new Token(Type.ATTEMPT1, '24,00'),
        new Token(Type.ATTEMPT2, '24,00'),
        new Token(Type.ATTEMPT3, '23,00'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '25'),
        new Token(Type.ATHLETE_FULL_NAME, 'Almasan Fabian'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SG Egelsbach'),
        new Token(Type.PERFORMANCE, '24,00'),
        new Token(Type.POINTS, '190'),
        new Token(Type.ATTEMPT1, '24,00'),
        new Token(Type.ATTEMPT2, '23,50'),
        new Token(Type.ATTEMPT3, '19,50'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '10'),
        new Token(Type.ATHLETE_FULL_NAME, 'Bürkle Jacob'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Langen'),
        new Token(Type.PERFORMANCE, '21,50'),
        new Token(Type.POINTS, '166'),
        new Token(Type.ATTEMPT1, '18,50'),
        new Token(Type.ATTEMPT2, '21,50'),
        new Token(Type.ATTEMPT3, '8,00'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '14'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schiller Leonard'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Langen'),
        new Token(Type.PERFORMANCE, '20,50'),
        new Token(Type.POINTS, '157'),
        new Token(Type.ATTEMPT1, '18,00'),
        new Token(Type.ATTEMPT2, '20,50'),
        new Token(Type.ATTEMPT3, '20,50'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
