import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 3.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/3.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'Kreiseinzelmeisterschaften'),
        new Token(Type.COMPETITION_CITY, 'Coesfeld'),
        new Token(Type.COMPETITION_VENUE, 'Coesfeld'),
        new Token(Type.COMPETITION_START_DATE, '17.09.2016'),
        new Token(Type.DISCIPLINE_NAME, 'Weitsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '17.09.2016'),
        new Token(Type.EVENT_TIME, '11:00'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '2168'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hörbelt Jonas'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Coesfeld'),
        new Token(Type.PERFORMANCE, '5,35'),
        new Token(Type.WIND, '-0,4'),
        new Token(Type.ATTEMPT1, '4,95'),
        new Token(Type.ATTEMPT2, '5,23'),
        new Token(Type.ATTEMPT3, '5,35'),
        new Token(Type.ATTEMPT4, '5,15'),
        new Token(Type.ATTEMPT5, '5,30'),
        new Token(Type.ATTEMPT6, '5,28'),
        new Token(Type.ATTEMPT_WIND1, '+0,1'),
        new Token(Type.ATTEMPT_WIND2, '0,0'),
        new Token(Type.ATTEMPT_WIND3, '-0,4'),
        new Token(Type.ATTEMPT_WIND4, '+1,2'),
        new Token(Type.ATTEMPT_WIND5, '-0,8'),
        new Token(Type.ATTEMPT_WIND6, '-0,1'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '2243'),
        new Token(Type.ATHLETE_FULL_NAME, 'Depke Tilo'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Ems Warendorf'),
        new Token(Type.PERFORMANCE, '5,23'),
        new Token(Type.WIND, '-0,3'),
        new Token(Type.ATTEMPT1, '4,94'),
        new Token(Type.ATTEMPT2, '4,99'),
        new Token(Type.ATTEMPT3, '5,23'),
        new Token(Type.ATTEMPT4, '5,04'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, '4,42'),
        new Token(Type.ATTEMPT_WIND1, '+0,2'),
        new Token(Type.ATTEMPT_WIND2, '0,0'),
        new Token(Type.ATTEMPT_WIND3, '-0,3'),
        new Token(Type.ATTEMPT_WIND4, '+0,4'),
        new Token(Type.ATTEMPT_WIND5, '0,0'),
        new Token(Type.ATTEMPT_WIND6, '+0,3'),
        new Token(Type.ATHLETE_POSITION, '7'),
        new Token(Type.ATHLETE_BIB, '2169'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schulze Baek Karsten'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Coesfeld'),
        new Token(Type.PERFORMANCE, '5,16'),
        new Token(Type.WIND, '+0,1'),
        new Token(Type.ATTEMPT1, '5,07'),
        new Token(Type.ATTEMPT2, '5,10'),
        new Token(Type.ATTEMPT3, '5,04'),
        new Token(Type.ATTEMPT4, '5,16'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, '4,74'),
        new Token(Type.ATTEMPT_WIND1, '+0,3'),
        new Token(Type.ATTEMPT_WIND2, '+0,3'),
        new Token(Type.ATTEMPT_WIND3, '+0,5'),
        new Token(Type.ATTEMPT_WIND4, '+0,1'),
        new Token(Type.ATTEMPT_WIND5, '+0,8'),
        new Token(Type.ATTEMPT_WIND6, '+0,4'),
        new Token(Type.ATHLETE_POSITION, '8'),
        new Token(Type.ATHLETE_BIB, '2246'),
        new Token(Type.ATHLETE_FULL_NAME, 'Höft Jacob'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Ems Warendorf'),
        new Token(Type.PERFORMANCE, '4,26'),
        new Token(Type.WIND, '+0,7'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, '4,12'),
        new Token(Type.ATTEMPT3, '4,20'),
        new Token(Type.ATTEMPT4, '4,25'),
        new Token(Type.ATTEMPT5, '4,26'),
        new Token(Type.ATTEMPT6, '4,14'),
        new Token(Type.ATTEMPT_WIND1, '-0,3'),
        new Token(Type.ATTEMPT_WIND2, '+0,6'),
        new Token(Type.ATTEMPT_WIND3, '-0,2'),
        new Token(Type.ATTEMPT_WIND4, '+0,3'),
        new Token(Type.ATTEMPT_WIND5, '+0,7'),
        new Token(Type.ATTEMPT_WIND6, '0,0'),
        new Token(Type.ATHLETE_BIB, '2292'),
        new Token(Type.ATHLETE_FULL_NAME, 'Heineke Gabriel'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SC Union 08 Lüdinghausen'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.DISCIPLINE_NAME, 'Kugelstoß'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '5000g'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '17.09.2016'),
        new Token(Type.EVENT_TIME, '16:00'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '2476'),
        new Token(Type.ATHLETE_FULL_NAME, 'Volks Josef'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Vreden'),
        new Token(Type.PERFORMANCE, '11,63'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, '11,37'),
        new Token(Type.ATTEMPT3, '11,38'),
        new Token(Type.ATTEMPT4, '11,18'),
        new Token(Type.ATTEMPT5, '11,21'),
        new Token(Type.ATTEMPT6, '11,63'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '2169'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schulze Baek Karsten'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Coesfeld'),
        new Token(Type.PERFORMANCE, '10,99'),
        new Token(Type.ATTEMPT1, '10,25'),
        new Token(Type.ATTEMPT2, '10,99'),
        new Token(Type.ATTEMPT3, '9,69'),
        new Token(Type.ATTEMPT4, '10,48'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, 'x'),
        new Token(Type.DISCIPLINE_NAME, 'Speerwurf'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '700g'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '17.09.2016'),
        new Token(Type.EVENT_TIME, '14:15'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '2168'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hörbelt Jonas'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Coesfeld'),
        new Token(Type.PERFORMANCE, '41,84'),
        new Token(Type.ATTEMPT1, '35,23'),
        new Token(Type.ATTEMPT2, '41,84'),
        new Token(Type.ATTEMPT3, '40,30'),
        new Token(Type.ATTEMPT4, '40,27'),
        new Token(Type.ATTEMPT5, '33,97'),
        new Token(Type.ATTEMPT6, 'x'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '2187'),
        new Token(Type.ATHLETE_FULL_NAME, 'Martschei Sebastian'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Coesfeld'),
        new Token(Type.PERFORMANCE, '38,45'),
        new Token(Type.ATTEMPT1, '36,76'),
        new Token(Type.ATTEMPT2, '32,33'),
        new Token(Type.ATTEMPT3, '34,89'),
        new Token(Type.ATTEMPT4, '33,34'),
        new Token(Type.ATTEMPT5, '35,16'),
        new Token(Type.ATTEMPT6, '38,45'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '2476'),
        new Token(Type.ATHLETE_FULL_NAME, 'Volks Josef'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Vreden'),
        new Token(Type.PERFORMANCE, '37,35'),
        new Token(Type.ATTEMPT1, '37,35'),
        new Token(Type.ATTEMPT2, '36,39'),
        new Token(Type.ATTEMPT3, '36,59'),
        new Token(Type.ATTEMPT4, 'x'),
        new Token(Type.ATTEMPT5, '36,25'),
        new Token(Type.ATTEMPT6, '35,03'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '452'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schüttert Joshua'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Coesfeld'),
        new Token(Type.PERFORMANCE, '37,34'),
        new Token(Type.ATTEMPT1, '37,22'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, '34,21'),
        new Token(Type.ATTEMPT4, '34,78'),
        new Token(Type.ATTEMPT5, '37,34'),
        new Token(Type.ATTEMPT6, '34,66'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '2243'),
        new Token(Type.ATHLETE_FULL_NAME, 'Depke Tilo'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Ems Warendorf'),
        new Token(Type.PERFORMANCE, '37,07'),
        new Token(Type.ATTEMPT1, '35,28'),
        new Token(Type.ATTEMPT2, '32,29'),
        new Token(Type.ATTEMPT3, '35,21'),
        new Token(Type.ATTEMPT4, '34,69'),
        new Token(Type.ATTEMPT5, '34,71'),
        new Token(Type.ATTEMPT6, '37,07'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
