import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 4.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/4.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'Nordhessische Hallenmeisterschaft'),
        new Token(Type.COMPETITION_CITY, 'Bad Sooden-Allendorf'),
        new Token(Type.COMPETITION_VENUE, 'Eilse-Sporthalle Bad Sooden-Allendorf'),
        new Token(Type.COMPETITION_START_DATE, '29.01.2017'),
        new Token(Type.DISCIPLINE_NAME, '60m'),
        new Token(Type.AGE_GROUP_NAME, 'Frauen'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '14:30'),
        new Token(Type.ROUND_NAME, 'Finale'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '52'),
        new Token(Type.ATHLETE_FULL_NAME, 'Klupsch Carolin'),
        new Token(Type.ATHLETE_YOB, '1996'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, '8,01'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '63'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hesse Jenny'),
        new Token(Type.ATHLETE_YOB, '1987'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Eder'),
        new Token(Type.PERFORMANCE, '8,39'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '134'),
        new Token(Type.ATHLETE_FULL_NAME, 'Pöppe Rabea'),
        new Token(Type.ATHLETE_YOB, '1995'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'MT Melsungen'),
        new Token(Type.PERFORMANCE, '8,43'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./I'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '49'),
        new Token(Type.ATHLETE_FULL_NAME, 'Grunwald Sara'),
        new Token(Type.ATHLETE_YOB, '1987'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, '8,68'),
        new Token(Type.GROUP_NUMBER_PLACE, '4./I'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '37'),
        new Token(Type.ATHLETE_FULL_NAME, 'Henkel Anissa'),
        new Token(Type.ATHLETE_YOB, '1996'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Kaufungen'),
        new Token(Type.PERFORMANCE, '8,85'),
        new Token(Type.GROUP_NUMBER_PLACE, '5./I'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '135'),
        new Token(Type.ATHLETE_FULL_NAME, 'Arend Lisa'),
        new Token(Type.ATHLETE_YOB, '1991'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'MT Melsungen'),
        new Token(Type.PERFORMANCE, '8,95'),
        new Token(Type.GROUP_NUMBER_PLACE, '6./I'),
        new Token(Type.DISCIPLINE_NAME, '60m Hürden'),
        new Token(Type.AGE_GROUP_NAME, 'Frauen'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '840mm'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '16:40'),
        new Token(Type.ROUND_NAME, 'Zeitläufe'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '52'),
        new Token(Type.ATHLETE_FULL_NAME, 'Klupsch Carolin'),
        new Token(Type.ATHLETE_YOB, '1996'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, '9,11'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '92'),
        new Token(Type.ATHLETE_FULL_NAME, 'Seminerio Chiara'),
        new Token(Type.ATHLETE_YOB, '1996'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Bad Sooden-Allendorf'),
        new Token(Type.PERFORMANCE, '11,08'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.DISCIPLINE_NAME, 'Hochsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Frauen'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '12:15'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '52'),
        new Token(Type.ATHLETE_FULL_NAME, 'Klupsch Carolin'),
        new Token(Type.ATHLETE_YOB, '1996'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, '1,64'),
        new Token(Type.HEIGHT, '1,55'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,58'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,61'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,64'),
        new Token(Type.HEIGHT_RESULT, 'XO'),
        new Token(Type.HEIGHT, '1,67'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '94'),
        new Token(Type.ATHLETE_FULL_NAME, 'Linnenkohl Hannah'),
        new Token(Type.ATHLETE_YOB, '1997'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Bad Sooden-Allendorf'),
        new Token(Type.PERFORMANCE, '1,52'),
        new Token(Type.HEIGHT, '1,43'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,46'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,49'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,52'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,55'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_BIB, '54'),
        new Token(Type.ATHLETE_FULL_NAME, 'Reitemeier Karin'),
        new Token(Type.ATHLETE_YOB, '1965'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.DISCIPLINE_NAME, 'Weitsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Frauen'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '17:00'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '52'),
        new Token(Type.ATHLETE_FULL_NAME, 'Klupsch Carolin'),
        new Token(Type.ATHLETE_YOB, '1996'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, '5,55'),
        new Token(Type.ATTEMPT1, '5,39'),
        new Token(Type.ATTEMPT2, '5,27'),
        new Token(Type.ATTEMPT3, '5,55'),
        new Token(Type.ATTEMPT4, '5,55'),
        new Token(Type.ATTEMPT5, '4,56'),
        new Token(Type.ATTEMPT6, 'x'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '63'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hesse Jenny'),
        new Token(Type.ATHLETE_YOB, '1987'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Eder'),
        new Token(Type.PERFORMANCE, '5,22'),
        new Token(Type.ATTEMPT1, 'x'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, '5,15'),
        new Token(Type.ATTEMPT4, '5,22'),
        new Token(Type.ATTEMPT5, '5,20'),
        new Token(Type.ATTEMPT6, 'x'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '49'),
        new Token(Type.ATHLETE_FULL_NAME, 'Grunwald Sara'),
        new Token(Type.ATHLETE_YOB, '1987'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, '4,82'),
        new Token(Type.ATTEMPT1, '3,95'),
        new Token(Type.ATTEMPT2, '4,82'),
        new Token(Type.ATTEMPT3, '4,63'),
        new Token(Type.ATTEMPT4, '4,62'),
        new Token(Type.ATTEMPT5, '4,28'),
        new Token(Type.ATTEMPT6, '4,40'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '92'),
        new Token(Type.ATHLETE_FULL_NAME, 'Seminerio Chiara'),
        new Token(Type.ATHLETE_YOB, '1996'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Bad Sooden-Allendorf'),
        new Token(Type.PERFORMANCE, '4,39'),
        new Token(Type.ATTEMPT1, '4,36'),
        new Token(Type.ATTEMPT2, '4,38'),
        new Token(Type.ATTEMPT3, '4,36'),
        new Token(Type.ATTEMPT4, '4,39'),
        new Token(Type.ATTEMPT5, '3,69'),
        new Token(Type.ATTEMPT6, 'x'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '58'),
        new Token(Type.ATHLETE_FULL_NAME, 'Grunwald Céline'),
        new Token(Type.ATHLETE_YOB, '1997'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, '4,17'),
        new Token(Type.ATTEMPT1, '3,82'),
        new Token(Type.ATTEMPT2, 'x'),
        new Token(Type.ATTEMPT3, 'x'),
        new Token(Type.ATTEMPT4, '4,05'),
        new Token(Type.ATTEMPT5, '4,17'),
        new Token(Type.ATTEMPT6, 'x'),
        new Token(Type.ATHLETE_BIB, '54'),
        new Token(Type.ATHLETE_FULL_NAME, 'Reitemeier Karin'),
        new Token(Type.ATHLETE_YOB, '1965'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SSC Vellmar von 1973 e.V.'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.ATHLETE_BIB, '64'),
        new Token(Type.ATHLETE_FULL_NAME, 'Strieder Lisa'),
        new Token(Type.ATHLETE_YOB, '1993'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Eder'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
