import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 5.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/5.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'Nordhessische Hallenmeisterschaft'),
        new Token(Type.COMPETITION_CITY, 'Bad Sooden-Allendorf'),
        new Token(Type.COMPETITION_VENUE, 'Eilse-Sporthalle Bad Sooden-Allendorf'),
        new Token(Type.COMPETITION_START_DATE, '29.01.2017'),
        new Token(Type.DISCIPLINE_NAME, '60m'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.GROUP_NUMBER, '2'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '15:20'),
        new Token(Type.GROUP_INFO, 'Es qualifizieren sich die 6 Zeitschnellsten (q) für Finale, um 16:10'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '2'),
        new Token(Type.ATHLETE_FULL_NAME, 'Gerke Julius'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV 09 Twiste'),
        new Token(Type.PERFORMANCE, '7,86'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '5'),
        new Token(Type.ATHLETE_FULL_NAME, 'Soose David'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'GSV Eintracht Baunatal'),
        new Token(Type.PERFORMANCE, '7,94'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '16'),
        new Token(Type.ATHLETE_FULL_NAME, 'Rimbach Moritz'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Alheimer/Rotenburg-Bebra'),
        new Token(Type.PERFORMANCE, '8,12'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '12'),
        new Token(Type.ATHLETE_FULL_NAME, 'Trebing Claudius'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TuSpo Borken'),
        new Token(Type.PERFORMANCE, '8,43'),
        new Token(Type.DISCIPLINE_NAME, '60m'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.GROUP_NUMBER, '3'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '15:25'),
        new Token(Type.GROUP_INFO, 'Es qualifizieren sich die 6 Zeitschnellsten (q) für Finale, um 16:10'),
        new Token(Type.DISCIPLINE_NAME, '60m'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '16:10'),
        new Token(Type.ROUND_NAME, 'Finale'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '88'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schade Hendrik'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAV Kassel'),
        new Token(Type.PERFORMANCE, '7,42'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '28'),
        new Token(Type.ATHLETE_FULL_NAME, 'Umbach Anton'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'ESV Jahn Treysa'),
        new Token(Type.PERFORMANCE, '7,54'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '7'),
        new Token(Type.ATHLETE_FULL_NAME, 'Eitzenhöfer Jonas'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Hessen 1846 Frankenberg'),
        new Token(Type.PERFORMANCE, '7,73'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./I'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '2'),
        new Token(Type.ATHLETE_FULL_NAME, 'Gerke Julius'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV 09 Twiste'),
        new Token(Type.PERFORMANCE, '7,85'),
        new Token(Type.GROUP_NUMBER_PLACE, '4./I'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '5'),
        new Token(Type.ATHLETE_FULL_NAME, 'Soose David'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'GSV Eintracht Baunatal'),
        new Token(Type.PERFORMANCE, '8,00'),
        new Token(Type.GROUP_NUMBER_PLACE, '5./I'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '16'),
        new Token(Type.ATHLETE_FULL_NAME, 'Rimbach Moritz'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Alheimer/Rotenburg-Bebra'),
        new Token(Type.PERFORMANCE, '8,24'),
        new Token(Type.GROUP_NUMBER_PLACE, '6./I'),
        new Token(Type.DISCIPLINE_NAME, '60m Hürden'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '914mm'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '16:30'),
        new Token(Type.ROUND_NAME, 'Zeitläufe'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '17'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kunkel Luca'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Alheimer/Rotenburg-Bebra'),
        new Token(Type.PERFORMANCE, '9,26'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.DISCIPLINE_NAME, 'Hochsprung'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U18'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '10:30'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '16'),
        new Token(Type.ATHLETE_FULL_NAME, 'Rimbach Moritz'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Alheimer/Rotenburg-Bebra'),
        new Token(Type.PERFORMANCE, '1,68'),
        new Token(Type.HEIGHT, '1,45'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,50'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,55'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,60'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,65'),
        new Token(Type.HEIGHT_RESULT, '-'),
        new Token(Type.HEIGHT, '1,68'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,71'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '17'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kunkel Luca'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Alheimer/Rotenburg-Bebra'),
        new Token(Type.PERFORMANCE, '1,60'),
        new Token(Type.HEIGHT, '1,60'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,65'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '79'),
        new Token(Type.ATHLETE_FULL_NAME, 'Niemeier Tim'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAV Kassel'),
        new Token(Type.PERFORMANCE, '1,60'),
        new Token(Type.HEIGHT, '1,55'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,60'),
        new Token(Type.HEIGHT_RESULT, 'XXO'),
        new Token(Type.HEIGHT, '1,65'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '121'),
        new Token(Type.ATHLETE_FULL_NAME, 'Ritter Christoph'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Reinhardswald'),
        new Token(Type.PERFORMANCE, '1,55'),
        new Token(Type.HEIGHT, '1,50'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,55'),
        new Token(Type.HEIGHT_RESULT, 'O'),
        new Token(Type.HEIGHT, '1,60'),
        new Token(Type.HEIGHT_RESULT, 'XXX'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
