import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 6.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/6.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'MTG U14 Hallensportfest'),
        new Token(Type.COMPETITION_CITY, 'Mannheim'),
        new Token(Type.COMPETITION_VENUE, 'OSP / LLZ Halle Mannheim'),
        new Token(Type.COMPETITION_START_DATE, '29.01.2017'),
        new Token(Type.DISCIPLINE_NAME, '60m'),
        new Token(Type.AGE_GROUP_NAME, '2. Lauf, W, WJU20, WJU18'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '13:40'),
        new Token(Type.ROUND_NAME, 'Zeitläufe'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '556'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wessolly Jessica-Bianca'),
        new Token(Type.ATHLETE_YOB, '1996'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'MTG Mannheim'),
        new Token(Type.PERFORMANCE, '7,83'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '552'),
        new Token(Type.ATHLETE_FULL_NAME, 'Münzer Lisa'),
        new Token(Type.ATHLETE_YOB, '1994'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'MTG Mannheim'),
        new Token(Type.PERFORMANCE, '7,96'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '548'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kränzle Celina'),
        new Token(Type.ATHLETE_YOB, '1997'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'MTG Mannheim'),
        new Token(Type.PERFORMANCE, '7,98'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./I'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '585'),
        new Token(Type.ATHLETE_FULL_NAME, 'Neumann Luisa'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Reisen'),
        new Token(Type.PERFORMANCE, '8,08'),
        new Token(Type.GROUP_NUMBER_PLACE, '4./I'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '587'),
        new Token(Type.ATHLETE_FULL_NAME, 'Stichling Katja'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Reisen'),
        new Token(Type.PERFORMANCE, '8,78'),
        new Token(Type.GROUP_NUMBER_PLACE, '5./I'),
        new Token(Type.DISCIPLINE_NAME, '200m'),
        new Token(Type.AGE_GROUP_NAME, 'W, WJU20, WJU18'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '15:40'),
        new Token(Type.ROUND_NAME, 'Zeitläufe'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '628'),
        new Token(Type.ATHLETE_FULL_NAME, 'Gonska Nadine'),
        new Token(Type.ATHLETE_YOB, '1990'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'MTG Mannheim'),
        new Token(Type.PERFORMANCE, '23,66'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./III'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '551'),
        new Token(Type.ATHLETE_FULL_NAME, 'Mergenthaler Hannah'),
        new Token(Type.ATHLETE_YOB, '1997'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'MTG Mannheim'),
        new Token(Type.PERFORMANCE, '24,46'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '556'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wessolly Jessica-Bianca'),
        new Token(Type.ATHLETE_YOB, '1996'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'MTG Mannheim'),
        new Token(Type.PERFORMANCE, '24,56'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '552'),
        new Token(Type.ATHLETE_FULL_NAME, 'Münzer Lisa'),
        new Token(Type.ATHLETE_YOB, '1994'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'MTG Mannheim'),
        new Token(Type.PERFORMANCE, '25,56'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./II'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '585'),
        new Token(Type.ATHLETE_FULL_NAME, 'Neumann Luisa'),
        new Token(Type.ATHLETE_YOB, '2001'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Reisen'),
        new Token(Type.PERFORMANCE, '25,65'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./II'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '599'),
        new Token(Type.ATHLETE_FULL_NAME, 'Dicks Grace'),
        new Token(Type.ATHLETE_YOB, '2000'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Unterländer LG'),
        new Token(Type.PERFORMANCE, '27,82'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./I'),
        new Token(Type.ATHLETE_POSITION, '7'),
        new Token(Type.ATHLETE_BIB, '525'),
        new Token(Type.ATHLETE_FULL_NAME, 'Rieß Emilia'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Region Karlsruhe'),
        new Token(Type.PERFORMANCE, '29,43'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./III'),
        new Token(Type.ATHLETE_POSITION, '8'),
        new Token(Type.ATHLETE_BIB, '587'),
        new Token(Type.ATHLETE_FULL_NAME, 'Stichling Katja'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Reisen'),
        new Token(Type.PERFORMANCE, '29,83'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./II'),
        new Token(Type.ATHLETE_POSITION, '9'),
        new Token(Type.ATHLETE_BIB, '520'),
        new Token(Type.ATHLETE_FULL_NAME, 'Gebreyesus Salina'),
        new Token(Type.ATHLETE_YOB, '2003'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Region Karlsruhe'),
        new Token(Type.PERFORMANCE, '31,21'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./III'),
        new Token(Type.DISCIPLINE_NAME, '4x200m'),
        new Token(Type.AGE_GROUP_NAME, 'Frauen'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '16:45'),
        new Token(Type.ROUND_NAME, 'Zeitläufe'),
        new Token(Type.TEAM_POSITION, '1'),
        new Token(Type.TEAM_NAME, 'MTG Mannheim 1'),
        new Token(Type.TEAM_COUNTRY, 'GER'),
        new Token(Type.TEAM_CLUB_NAME, 'MTG Mannheim'),
        new Token(Type.PERFORMANCE, '1:38,88'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_BIB, '556'),
        new Token(Type.ATHLETE_FULL_NAME, 'Wessolly Jessica-Bianca'),
        new Token(Type.ATHLETE_YOB, '1996'),
        new Token(Type.ATHLETE_BIB, '551'),
        new Token(Type.ATHLETE_FULL_NAME, 'Mergenthaler Hannah'),
        new Token(Type.ATHLETE_YOB, '1997'),
        new Token(Type.ATHLETE_BIB, '552'),
        new Token(Type.ATHLETE_FULL_NAME, 'Münzer Lisa'),
        new Token(Type.ATHLETE_YOB, '1994'),
        new Token(Type.ATHLETE_BIB, '548'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kränzle Celina'),
        new Token(Type.ATHLETE_YOB, '1997'),
        new Token(Type.DISCIPLINE_NAME, 'Kugelstoß'),
        new Token(Type.AGE_GROUP_NAME, 'W'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '11:20'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '622'),
        new Token(Type.ATHLETE_FULL_NAME, 'Ogunleye Yemisi'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'MTG Mannheim'),
        new Token(Type.PERFORMANCE, '14,34'),
        new Token(Type.ATTEMPT1, '13,86'),
        new Token(Type.ATTEMPT2, '14,34'),
        new Token(Type.ATTEMPT3, '13,17'),
        new Token(Type.ATTEMPT4, '13,72'),
        new Token(Type.ATTEMPT5, 'x'),
        new Token(Type.ATTEMPT6, 'x'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '623'),
        new Token(Type.ATHLETE_FULL_NAME, 'Trzenski Alexandra'),
        new Token(Type.ATHLETE_YOB, '1996'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'MTG Mannheim'),
        new Token(Type.PERFORMANCE, '8,04'),
        new Token(Type.ATTEMPT1, '7,83'),
        new Token(Type.ATTEMPT2, '7,71'),
        new Token(Type.ATTEMPT3, '7,69'),
        new Token(Type.ATTEMPT4, '7,21'),
        new Token(Type.ATTEMPT5, '8,04'),
        new Token(Type.ATTEMPT6, '7,40'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
