import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 7.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/7.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'MTG U14 Hallensportfest'),
        new Token(Type.COMPETITION_CITY, 'Mannheim'),
        new Token(Type.COMPETITION_VENUE, 'OSP / LLZ Halle Mannheim'),
        new Token(Type.COMPETITION_START_DATE, '29.01.2017'),
        new Token(Type.DISCIPLINE_NAME, '60m'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend M12'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '13:15'),
        new Token(Type.ROUND_NAME, 'Finale'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '81'),
        new Token(Type.ATHLETE_FULL_NAME, 'Allenberger Jann'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'MTG Mannheim'),
        new Token(Type.PERFORMANCE, '8,86'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '529'),
        new Token(Type.ATHLETE_FULL_NAME, 'Alt Jonathan'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, '9,00'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '503'),
        new Token(Type.ATHLETE_FULL_NAME, 'Stoklas Levin'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'DJK Hockenheim'),
        new Token(Type.PERFORMANCE, '9,07'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./I'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '532'),
        new Token(Type.ATHLETE_FULL_NAME, 'Mühlmann Cedric'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, '9,20'),
        new Token(Type.GROUP_NUMBER_PLACE, '4./I'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '582'),
        new Token(Type.ATHLETE_FULL_NAME, 'Mikeska Levi'),
        new Token(Type.ATHLETE_YOB, '2006'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Reisen'),
        new Token(Type.PERFORMANCE, '9,25'),
        new Token(Type.GROUP_NUMBER_PLACE, '5./I'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '606'),
        new Token(Type.ATHLETE_FULL_NAME, 'Grabner Frederik'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG 1862 Weinheim'),
        new Token(Type.PERFORMANCE, '9,35'),
        new Token(Type.GROUP_NUMBER_PLACE, '6./I'),
        new Token(Type.ATHLETE_POSITION, '7'),
        new Token(Type.ATHLETE_BIB, '583'),
        new Token(Type.ATHLETE_FULL_NAME, 'Sönmezciec Ardahan'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Reisen'),
        new Token(Type.PERFORMANCE, '9,46'),
        new Token(Type.GROUP_NUMBER_PLACE, '7./I'),
        new Token(Type.ATHLETE_POSITION, '8'),
        new Token(Type.ATHLETE_BIB, '605'),
        new Token(Type.ATHLETE_FULL_NAME, 'Daners Bennet'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG 1862 Weinheim'),
        new Token(Type.PERFORMANCE, '9,47'),
        new Token(Type.GROUP_NUMBER_PLACE, '8./I'),
        new Token(Type.DISCIPLINE_NAME, '800m'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend M12'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '16:30'),
        new Token(Type.ROUND_NAME, 'Zeitläufe'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '607'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hoffmann Julius'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG 1862 Weinheim'),
        new Token(Type.PERFORMANCE, '2:40,65'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '493'),
        new Token(Type.ATHLETE_FULL_NAME, 'Langlouis Eric'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG 78 Heidelberg'),
        new Token(Type.PERFORMANCE, '2:40,99'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '513'),
        new Token(Type.ATHLETE_FULL_NAME, 'Beeh Diego'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Region Karlsruhe'),
        new Token(Type.PERFORMANCE, '2:41,44'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./I'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '565'),
        new Token(Type.ATHLETE_FULL_NAME, 'Bolle Max'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Neckarsulmer Sport-Union'),
        new Token(Type.PERFORMANCE, '2:50,48'),
        new Token(Type.GROUP_NUMBER_PLACE, '4./I'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '489'),
        new Token(Type.ATHLETE_FULL_NAME, 'Buselmeier Jakob'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG 78 Heidelberg'),
        new Token(Type.PERFORMANCE, '2:50,90'),
        new Token(Type.GROUP_NUMBER_PLACE, '5./I'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '465'),
        new Token(Type.ATHLETE_FULL_NAME, 'Nikitin Artur'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SCL Heel Baden-Baden'),
        new Token(Type.PERFORMANCE, '2:53,22'),
        new Token(Type.GROUP_NUMBER_PLACE, '6./I'),
        new Token(Type.ATHLETE_POSITION, '7'),
        new Token(Type.ATHLETE_BIB, '614'),
        new Token(Type.ATHLETE_FULL_NAME, 'Burchhardt Marcel'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TB Wilferdingen'),
        new Token(Type.PERFORMANCE, '2:57,99'),
        new Token(Type.GROUP_NUMBER_PLACE, '7./I'),
        new Token(Type.ATHLETE_POSITION, '8'),
        new Token(Type.ATHLETE_BIB, '558'),
        new Token(Type.ATHLETE_FULL_NAME, 'Rudolph Tom'),
        new Token(Type.ATHLETE_YOB, '2006'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'PSG Mannheim'),
        new Token(Type.PERFORMANCE, '3:22,60'),
        new Token(Type.GROUP_NUMBER_PLACE, '8./I'),
        new Token(Type.ATHLETE_POSITION, '9'),
        new Token(Type.ATHLETE_BIB, '557'),
        new Token(Type.ATHLETE_FULL_NAME, 'Gudd Elias'),
        new Token(Type.ATHLETE_YOB, '2006'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'PSG Mannheim'),
        new Token(Type.PERFORMANCE, '3:35,89'),
        new Token(Type.GROUP_NUMBER_PLACE, '9./I'),
        new Token(Type.SPLIT_GROUP, '1'),
        new Token(Type.SPLIT_DISTANCE, '200m'),
        new Token(Type.SPLIT_TIME, '41,19'),
        new Token(Type.ATHLETE_BIB, '614'),
        new Token(Type.ATHLETE_FULL_NAME, 'Burchhardt Marcel'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.SPLIT_DISTANCE, '400m'),
        new Token(Type.SPLIT_TIME, '1:21,92'),
        new Token(Type.ATHLETE_BIB, '607'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hoffmann Julius'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.SPLIT_DISTANCE, '600m'),
        new Token(Type.SPLIT_TIME, '2:03,97'),
        new Token(Type.ATHLETE_BIB, '607'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hoffmann Julius'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.DISCIPLINE_NAME, '60m Hürden'),
        new Token(Type.AGE_GROUP_NAME, 'Jugend M12'),
        new Token(Type.DISCIPLINE_ADDITIONAL_INFO, '686mm'),
        new Token(Type.EVENT_DATE, '29.01.2017'),
        new Token(Type.EVENT_TIME, '14:30'),
        new Token(Type.ROUND_NAME, 'Finale'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '484'),
        new Token(Type.ATHLETE_FULL_NAME, 'Holzwarth Fabio'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Eppingen'),
        new Token(Type.PERFORMANCE, '10,99'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '529'),
        new Token(Type.ATHLETE_FULL_NAME, 'Alt Jonathan'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, '11,01'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '532'),
        new Token(Type.ATHLETE_FULL_NAME, 'Mühlmann Cedric'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'USC Mainz'),
        new Token(Type.PERFORMANCE, '11,13'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./I'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '490'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hufnagel Mika'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSG 78 Heidelberg'),
        new Token(Type.PERFORMANCE, '11,87'),
        new Token(Type.GROUP_NUMBER_PLACE, '4./I'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '463'),
        new Token(Type.ATHLETE_FULL_NAME, 'Keck Jonas'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SCL Heel Baden-Baden'),
        new Token(Type.PERFORMANCE, '12,95'),
        new Token(Type.GROUP_NUMBER_PLACE, '5./I'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '627'),
        new Token(Type.ATHLETE_FULL_NAME, 'Reichert Leonard'),
        new Token(Type.ATHLETE_YOB, '2005'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SV 1899 Langensteinbach'),
        new Token(Type.PERFORMANCE, '13,14'),
        new Token(Type.GROUP_NUMBER_PLACE, '6./I'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
