import path from 'path';
import fs from 'fs';
import { expect } from 'chai';
import pdf from 'oadf-pdf-converter';
import Lexer from '../../src/Lexer';
import Token, { TYPES as Type } from '../../src/Token';

describe('SELTEC 3 PDF Lexer 8.pdf', () => {
  it('should create the correct tokens', (done) => {
    const filePath = path.join(process.cwd(), 'test/lexer/fixtures/8.pdf');
    const data = new Uint8Array(fs.readFileSync(filePath));
    pdf(data).then((pages) => {
      const tokens = Lexer(pages);
      expect(tokens).to.deep.equal([
        new Token(Type.COMPETITION_NAME, 'Rheinland-Pfalz Hallenmeisterschaften U20, U18'),
        new Token(Type.COMPETITION_CITY, 'Ludwigshafen'),
        new Token(Type.COMPETITION_VENUE, 'Leichtathletik Halle Ludwigshafen'),
        new Token(Type.COMPETITION_START_DATE, '22.01.2017'),
        new Token(Type.DISCIPLINE_NAME, '60m'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U20'),
        new Token(Type.GROUP_NUMBER, '1'),
        new Token(Type.EVENT_DATE, '22.01.2017'),
        new Token(Type.EVENT_TIME, '14:10'),
        new Token(Type.GROUP_INFO, 'Es qualifizieren sich die 6 Zeitschnellsten (q) für Finale, um 15:25'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '356'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kolberg Lennert'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Kreis Ahrweiler'),
        new Token(Type.PERFORMANCE, '7,10'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '426'),
        new Token(Type.ATHLETE_FULL_NAME, 'Jedlitschka Tilman'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TPSV Enkenbach'),
        new Token(Type.PERFORMANCE, '7,26'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '466'),
        new Token(Type.ATHLETE_FULL_NAME, 'Phan Tony'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Lahn-Aar-Esterau'),
        new Token(Type.PERFORMANCE, '7,29'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '638'),
        new Token(Type.ATHLETE_FULL_NAME, 'Morgenschweis Simon'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Westerwald'),
        new Token(Type.PERFORMANCE, '7,51'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '484'),
        new Token(Type.ATHLETE_FULL_NAME, 'Giese Andreas'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Maifeld-Pellenz'),
        new Token(Type.PERFORMANCE, '7,61'),
        new Token(Type.ATHLETE_BIB, '588'),
        new Token(Type.ATHLETE_FULL_NAME, 'Jung Sven'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Rheinzabern'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.DISCIPLINE_NAME, '60m'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U20'),
        new Token(Type.GROUP_NUMBER, '2'),
        new Token(Type.EVENT_DATE, '22.01.2017'),
        new Token(Type.EVENT_TIME, '14:14'),
        new Token(Type.GROUP_INFO, 'Es qualifizieren sich die 6 Zeitschnellsten (q) für Finale, um 15:25'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '481'),
        new Token(Type.ATHLETE_FULL_NAME, 'Tselios Konstantinos'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GRE'),
        new Token(Type.ATHLETE_CLUB_NAME, 'ABC Ludwigshafen'),
        new Token(Type.PERFORMANCE, '7,21'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '651'),
        new Token(Type.ATHLETE_FULL_NAME, 'Klein Jonas'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Zweibrücken'),
        new Token(Type.PERFORMANCE, '7,24'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '556'),
        new Token(Type.ATHLETE_FULL_NAME, 'Klundt Philipp'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Nussdorf'),
        new Token(Type.PERFORMANCE, '7,37'),
        new Token(Type.QUALIFIED, 'q'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '411'),
        new Token(Type.ATHLETE_FULL_NAME, 'Jung Max'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LCO Edenkoben'),
        new Token(Type.PERFORMANCE, '7,59'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '635'),
        new Token(Type.ATHLETE_FULL_NAME, 'Lichtenthäler Lorenz'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Westerwald'),
        new Token(Type.PERFORMANCE, '7,61'),
        new Token(Type.ATHLETE_BIB, '384'),
        new Token(Type.ATHLETE_FULL_NAME, 'Hassane Jamal'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Bernkastel/Wittlich'),
        new Token(Type.PERFORMANCE, 'n.a.'),
        new Token(Type.DISCIPLINE_NAME, '60m'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U20'),
        new Token(Type.EVENT_DATE, '22.01.2017'),
        new Token(Type.EVENT_TIME, '15:25'),
        new Token(Type.ROUND_NAME, 'Finale'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '356'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kolberg Lennert'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Kreis Ahrweiler'),
        new Token(Type.PERFORMANCE, '7,08'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '481'),
        new Token(Type.ATHLETE_FULL_NAME, 'Tselios Konstantinos'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GRE'),
        new Token(Type.ATHLETE_CLUB_NAME, 'ABC Ludwigshafen'),
        new Token(Type.PERFORMANCE, '7,11'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '651'),
        new Token(Type.ATHLETE_FULL_NAME, 'Klein Jonas'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Zweibrücken'),
        new Token(Type.PERFORMANCE, '7,17'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./I'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '466'),
        new Token(Type.ATHLETE_FULL_NAME, 'Phan Tony'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Lahn-Aar-Esterau'),
        new Token(Type.PERFORMANCE, '7,24'),
        new Token(Type.GROUP_NUMBER_PLACE, '4./I'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '426'),
        new Token(Type.ATHLETE_FULL_NAME, 'Jedlitschka Tilman'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TPSV Enkenbach'),
        new Token(Type.PERFORMANCE, '7,28'),
        new Token(Type.GROUP_NUMBER_PLACE, '5./I'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '556'),
        new Token(Type.ATHLETE_FULL_NAME, 'Klundt Philipp'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Nussdorf'),
        new Token(Type.PERFORMANCE, '7,48'),
        new Token(Type.GROUP_NUMBER_PLACE, '6./I'),
        new Token(Type.DISCIPLINE_NAME, '200m'),
        new Token(Type.AGE_GROUP_NAME, 'Männliche Jugend U20'),
        new Token(Type.EVENT_DATE, '22.01.2017'),
        new Token(Type.EVENT_TIME, '16:45'),
        new Token(Type.ATHLETE_POSITION, '1'),
        new Token(Type.ATHLETE_BIB, '651'),
        new Token(Type.ATHLETE_FULL_NAME, 'Klein Jonas'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LAZ Zweibrücken'),
        new Token(Type.PERFORMANCE, '22,74'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./III'),
        new Token(Type.ATHLETE_POSITION, '2'),
        new Token(Type.ATHLETE_BIB, '451'),
        new Token(Type.ATHLETE_FULL_NAME, 'Jacob Jan Philipp'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, '1.FC Kaiserslautern'),
        new Token(Type.PERFORMANCE, '23,17'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./III'),
        new Token(Type.ATHLETE_POSITION, '3'),
        new Token(Type.ATHLETE_BIB, '466'),
        new Token(Type.ATHLETE_FULL_NAME, 'Phan Tony'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Lahn-Aar-Esterau'),
        new Token(Type.PERFORMANCE, '23,70'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./I'),
        new Token(Type.ATHLETE_POSITION, '4'),
        new Token(Type.ATHLETE_BIB, '484'),
        new Token(Type.ATHLETE_FULL_NAME, 'Giese Andreas'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Maifeld-Pellenz'),
        new Token(Type.PERFORMANCE, '23,71'),
        new Token(Type.GROUP_NUMBER_PLACE, '1./II'),
        new Token(Type.ATHLETE_POSITION, '5'),
        new Token(Type.ATHLETE_BIB, '617'),
        new Token(Type.ATHLETE_FULL_NAME, 'Fusenig Nicolas'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'Post-Sportverein Trier'),
        new Token(Type.PERFORMANCE, '23,96'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./II'),
        new Token(Type.ATHLETE_POSITION, '6'),
        new Token(Type.ATHLETE_BIB, '641'),
        new Token(Type.ATHLETE_FULL_NAME, 'Schwarz Jan-Matthias'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Westerwald'),
        new Token(Type.PERFORMANCE, '25,09'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./II'),
        new Token(Type.ATHLETE_POSITION, '7'),
        new Token(Type.ATHLETE_BIB, '425'),
        new Token(Type.ATHLETE_FULL_NAME, 'Lutterbach Raphael'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV Emmelshausen'),
        new Token(Type.PERFORMANCE, '25,11'),
        new Token(Type.GROUP_NUMBER_PLACE, '2./I'),
        new Token(Type.ATHLETE_POSITION, '8'),
        new Token(Type.ATHLETE_BIB, '401'),
        new Token(Type.ATHLETE_FULL_NAME, 'Gilles Simon'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'SpVgg 04/13 Burgbrohl'),
        new Token(Type.PERFORMANCE, '25,36'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./III'),
        new Token(Type.ATHLETE_POSITION, '9'),
        new Token(Type.ATHLETE_BIB, '478'),
        new Token(Type.ATHLETE_FULL_NAME, 'Okcu Ferhat'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'TUR'),
        new Token(Type.ATHLETE_CLUB_NAME, 'ABC Ludwigshafen'),
        new Token(Type.PERFORMANCE, '25,39'),
        new Token(Type.GROUP_NUMBER_PLACE, '4./II'),
        new Token(Type.ATHLETE_POSITION, '10'),
        new Token(Type.ATHLETE_BIB, '389'),
        new Token(Type.ATHLETE_FULL_NAME, 'Raadts Sebastian'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Bernkastel/Wittlich'),
        new Token(Type.PERFORMANCE, '25,40'),
        new Token(Type.GROUP_NUMBER_PLACE, '3./I'),
        new Token(Type.ATHLETE_POSITION, '11'),
        new Token(Type.ATHLETE_BIB, '528'),
        new Token(Type.ATHLETE_FULL_NAME, 'Yesilgöz Yannick'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TSV SCHOTT Mainz'),
        new Token(Type.PERFORMANCE, '27,02'),
        new Token(Type.GROUP_NUMBER_PLACE, '4./I'),
        new Token(Type.ATHLETE_BIB, '382'),
        new Token(Type.ATHLETE_FULL_NAME, 'Gierens Fabian'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Bernkastel/Wittlich'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.COMMENT, 'Zeitnahme ausgefallen - kein Wiederholungslauf'),
        new Token(Type.ATHLETE_BIB, '433'),
        new Token(Type.ATHLETE_FULL_NAME, 'Gropp Sebastian'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TV Gimmeldingen'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.ATHLETE_BIB, '356'),
        new Token(Type.ATHLETE_FULL_NAME, 'Kolberg Lennert'),
        new Token(Type.ATHLETE_YOB, '1998'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'LG Kreis Ahrweiler'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.COMMENT, 'Zeitnahme ausgefallen - kein Wiederholungslauf'),
        new Token(Type.ATHLETE_BIB, '426'),
        new Token(Type.ATHLETE_FULL_NAME, 'Jedlitschka Tilman'),
        new Token(Type.ATHLETE_YOB, '1999'),
        new Token(Type.ATHLETE_COUNTRY, 'GER'),
        new Token(Type.ATHLETE_CLUB_NAME, 'TPSV Enkenbach'),
        new Token(Type.PERFORMANCE, 'abg.'),
        new Token(Type.COMMENT, 'Zeitnahme ausgefallen - kein Wiederholungslauf'),
        new Token(Type.END),
      ]);
      done();
    }).catch((e) => {
      done(e);
    });
  });
});
